### ISSUE TITLE
Adding Reaticulate JSFX reloads all FX on track

### ISSUE THREAD

**Issue by jtackaberry** [jtackaberry/reaticulate#1]
When clicking the "Add Reaticulate FX" button, all the FX on the track get reloaded one by one as Reaticulate creeps up slot by slot until it reaches the top of the chain.

**Comment by aaronventure** [comment]
Could there be an option to disable auto-arrange Reaticulate FX to the top? I have a mixer open all the time on a separate window so manual re-arranging of the chain is a non-issue.
