### ISSUE TITLE
"Autostart: Never" doesn't work / isn't persistent

### ISSUE THREAD

**Issue by DoubleGrit** [jtackaberry/reaticulate#107]
Achieved by:
Set Autostart to "Never",
Restarting Reaper 
Run reaticulate_start 
Open reaticulate settings again 

Autostart setting back at "When Reaper starts"

**Comment by jtackaberry** [comment]
Confirmed, thanks.  It was a regression caused by 1de12f4 which clearly was poorly tested.

I'll cut a bugfix release of the 0.4.x series in a few days, and this fix will land in that release.

Cheers @DoubleGrit
