### ISSUE TITLE
A Few Banks

### ISSUE THREAD

**Issue by DoubleGrit** [jtackaberry/reaticulate#108]
Cinesamples Cinebrass Core
Cinesamples Cinebrass Pro
ProjectSam Orchestral Brass Classic

Many thanks for your work Tack, this whole project is a huge help to me 👍 

Cheers
Jack

[Cinesamples Cinebrass Core.txt](https://github.com/jtackaberry/reaticulate/files/5092153/Cinesamples.Cinebrass.Core.txt)
[Cinesamples Cinebrass Pro.txt](https://github.com/jtackaberry/reaticulate/files/5092154/Cinesamples.Cinebrass.Pro.txt)
[Orchestral Brass Classic.txt](https://github.com/jtackaberry/reaticulate/files/5092466/Orchestral.Brass.Classic.txt)

**Comment by jtackaberry** [comment]
@DoubleGrit thanks very much for the contribution!
