### ISSUE TITLE
Submitting VSL Reaticulate banks for the userbanks page

### ISSUE THREAD

**Issue by seventh-sam** [jtackaberry/reaticulate#110]
I've created a large reaticulate.reabank file for the following libraries that I would like to submit to the user banks section of this Github:

- All VI String Libraries (Full versions)
- All VI Brass Libraries (Full versions) except Dimension Brass
- All VI Woodwind Libraries (Full versions) except Historic Woodwinds I-III
- All VI Percussion Libraries, including Elements (Full versions)
- All VI Keyboard Libraries (Full versions)
- Synchronized Dimensions Strings I-III, Synchronized Dimension Brass I-II, Synchronized Appassionata Strings, Synchronized Solo Strings

Link to detailed instructions on the set-up here: 
https://www.vsl.co.at/community/posts/t53083-Comprehensive-Articulation-Management-System-for-VSL-Libraries--for-REAPER-users#post287931

Files here:
[VSL Libraries - Reaticulate Banks JUNE 2020.zip](https://github.com/jtackaberry/reaticulate/files/5143377/VSL.Libraries.-.Reaticulate.Banks.JUNE.2020.zip)

Thanks!

**Comment by jtackaberry** [comment]
Holy crap, this is a Herculean effort!  Almost 20k lines, wow!  Did you hand sling this entire thing, or write a program to generate it? :)

I'm thinking I may slice and dice your monolithic bank into smaller consumable units.  Would this best be done based on how you itemized them above?  Generally it makes sense to separate things out based on how the libraries are sold, although given the sheer number of banks in your submission, grouping by family like that may be more approachable.

Thoughts?

**Comment by seventh-sam** [comment]
I did the whole thing by hand, with the help of a podcast or two (or ten).
:-)  Speaking of herculean effort, I really can't thank you enough for all
of *your* effort in making Reaticulate.  I'm not exaggerating when I say
it's completely changed how I work and I can't imagine making music without
it.  Thank you, thank you, thank you SO much.  If there's anything I can do
to help (other than recommend it to people and upload banks I make), please
let me know.

As for these banks, I think your idea is a good one.  VSL sells their
products on a mostly instrument to instrument basis (hence the enormous
amount of banks), so slicing it down into the individual product lines
would generate something like 40+ files and make the github list waaaaaaay
too long.  I think grouping them by families and labeling them as such
(i.e. All VI Woodwind libraries, All VI Brass libraries, etc.) makes more
sense.  The user will have to search the file for the relevant banks they
own and copy and paste, but they'd have to do that anyway with what I
made...

I'd be happy to do this!  Shall I go ahead and re-submit that way?

- Sam

seventhsam.com

**Comment by jtackaberry** [comment]
> I'd be happy to do this! Shall I go ahead and re-submit that way?

That would be extremely appreciated!  Thanks terrible, @seventh-sam

**Comment by seventh-sam** [comment]
Alright, here you go!  Sorry that took so long...

[VSL Libraries - Brass.zip](https://github.com/jtackaberry/reaticulate/files/5215431/VSL.Libraries.-.Brass.zip)
[VSL Libraries - Keyboards.zip](https://github.com/jtackaberry/reaticulate/files/5215432/VSL.Libraries.-.Keyboards.zip)
[VSL Libraries - Percussion.zip](https://github.com/jtackaberry/reaticulate/files/5215433/VSL.Libraries.-.Percussion.zip)
[VSL Libraries - Strings.zip](https://github.com/jtackaberry/reaticulate/files/5215434/VSL.Libraries.-.Strings.zip)
[VSL Libraries - Various Synchronized.zip](https://github.com/jtackaberry/reaticulate/files/5215435/VSL.Libraries.-.Various.Synchronized.zip)
[VSL Libraries - Woodwinds.zip](https://github.com/jtackaberry/reaticulate/files/5215436/VSL.Libraries.-.Woodwinds.zip)

The original post's description and links should suffice for explaining the content of each zip file.  Even so, I've included a README in each one.

Let me know if you need anything else!

**Comment by jtackaberry** [comment]
Thanks @seventh-sam, I've committed the banks now.  I decided not to also include all the VI presets in the git repo here but added the link to all the banks.

Thanks tremendously for this contribution!  It will be a great help to many.
