### ISSUE TITLE
Reabank: CineWinds Core (complete version)

### ISSUE THREAD

**Issue by StephanRoemer** [jtackaberry/reaticulate#111]
Hey Jason,

I created a new version for CineWinds that includes all instruments and also the rather hidden double and tripple tongue articulations.

> //############################################################################
> // Library : CineSamples CineWinds Core 
> //----------------------------------------------------------------------------
> // Author: Stephan Römer
> //############################################################################
> 
> 
> //! g="Cinesamples/CineWinds Core" n="CWC - Piccolo Flute"
> Bank 19 1 CWC - Piccolo Flute
> 
> //! c=legato i=legato o=note:36
> 20 legato
> //! c=short i=marcato-quarter o=note:41
> 52 marcato
> //! c=short i=tenuto-eighth o=note:40
> 50 tenuto
> //! c=short i=staccato o=note:38
> 40 staccato
> //! c=short i=multitongued o=note:38/note-hold:37
> 75 staccato double tongue
> //! c=short i=multitongued o=note:38/note-hold:39
> 77 staccato triple tongue
> //! c=long i=trill-min2 o=note:43
> 70 trill m2
> //! c=long i=trill-maj2 o=note:45
> 71 trill M2
> 
> //----------------------------------------------------------------------------
> //! g="Cinesamples/CineWinds Core" n="CWC - Flute"
> //! clone="Cinesamples/CineWinds Core/CWC - Piccolo Flute"
> Bank 19 2 CWC - Flute 
> 
> //----------------------------------------------------------------------------
> //! g="Cinesamples/CineWinds Core" n="CWC - Oboe 1"
> //! clone="Cinesamples/CineWinds Core/CWC - Piccolo"
> Bank 19 3 CWC - Oboe 1
> 
> //! g="Cinesamples/CineWinds Core" n="CWC - Oboe 2"
> Bank 19 4 CWC - Oboe 2
> 
> //! c=legato i=legato o=note:36
> 20 legato
> //! c=short i=marcato-quarter o=note:40
> 52 marcato
> //! c=short i=staccato o=note:38
> 40 staccato
> //! c=short i=multitongued o=note:38/note-hold:37
> 75 staccato double tongue
> //! c=short i=multitongued o=note:38/note-hold:39
> 77 staccato triple tongue
> 
> //----------------------------------------------------------------------------
> //! g="Cinesamples/CineWinds Core" n="CWC - Clarinet"
> Bank 19 5 CWC - Clarinet
> 
> //! c=legato i=legato o=note:24
> 20 legato
> //! c=short i=marcato-quarter o=note:29
> 52 marcato
> //! c=short i=tenuto-eighth o=note:28
> 50 tenuto
> //! c=short i=staccato o=note:26
> 40 staccato
> //! c=short i=multitongued o=note:26/note-hold:37
> 75 staccato double tongue
> //! c=short i=multitongued o=note:26/note-hold:39
> 77 staccato triple tongue
> //! c=long i=trill-min2 o=note:31
> 70 trill m2
> //! c=long i=trill-maj2 o=note:33
> 71 trill M2
> 
> //----------------------------------------------------------------------------
> //! g="Cinesamples/CineWinds Core" n="CWC - Bassoon"
> Bank 19 6 CWC - Bassoon
> 
> //! c=legato i=legato o=note:12
> 20 legato
> //! c=short i=marcato-quarter o=note:17
> 52 marcato
> //! c=short i=tenuto-eighth o=note:16
> 50 tenuto
> //! c=short i=staccato o=note:14
> 40 staccato
> //! c=short i=multitongued o=note:14/note-hold:25
> 75 staccato double tongue
> //! c=short i=multitongued o=note:14/note-hold:27
> 77 staccato triple tongue
> //! c=long i=trill-min2 o=note:19
> 70 trill m2
> //! c=long i=trill-maj2 o=note:21
> 71 trill M2
> 
> 
> //----------------------------------------------------------------------------
> //! g="Cinesamples/CineWinds Core" n="CWC - Full Ensemble"
> Bank 19 7 CWC - Full Ensemble
> 
> //! c=long i=note-whole o=note:12
> 1 sustain
> //! c=short i=marcato-quarter o=note:17
> 52 marcato
> //! c=short i=tenuto-eighth o=note:16
> 50 tenuto
> //! c=short i=staccato o=note:14
> 40 staccato
> //! c=short i=multitongued o=note:14/note-hold:25
> 75 staccato double tongue
> //! c=short i=multitongued o=note:14/note-hold:27
> 77 staccato triple tongue
> //! c=long i=trill-min2 o=note:19
> 70 trill m2
> //! c=long i=trill-maj2 o=note:21
> 71 trill M2

**Comment by jtackaberry** [comment]
Thanks Stephan :)
