### ISSUE TITLE
Spitfire Studio Woodwinds

### ISSUE THREAD

**Issue by robinboncoeur** [jtackaberry/reaticulate#117]
Just saw that others were posting their banks contributions directly here, so I thought I'd make it easier for you, Jason, and do the same. 
[SFStudioWoods.zip](https://github.com/jtackaberry/reaticulate/files/5222338/SFStudioWoods.zip)

These have been tested to the best of my ability and should be clean. Thanks for your patience on them.

**Comment by jtackaberry** [comment]
Thanks very much for the contribution, @robinboncoeur. :)

**Comment by robinboncoeur** [comment]
You're quite welcome, Jason - hope to have a good chunk of the NI Kontakt Factory instruments for you, but unless you're happy with drips-and-drabs, I'll try to have a more comprehensive collection for you.

**Comment by jtackaberry** [comment]
One bigger chunk is easier for me to process 👍 

I'm actually going to reopen this since I haven't had a chance yet to commit your submission to the repository, so leaving this open helps remind me I still need to do that. :)

**Comment by jtackaberry** [comment]
Committed (with a few small tweaks).  Thanks @robinboncoeur!

**Comment by robinboncoeur** [comment]
Thank you for the tweaks :)
