### ISSUE TITLE
Garritan Personal Orchestra reabank (GPO 5) 

### ISSUE THREAD

**Issue by benignoc** [jtackaberry/reaticulate#12]
It should also work on most of GPO 4 I think.

Had to change extension to .txt

I included all the Keyswitching instruments. Let me know if there is any problem.

[GPO5.txt](https://github.com/jtackaberry/reaticulate/files/1511603/GPO5.txt)

**Comment by jtackaberry** [comment]
Thanks for this, Benigno!  It's easy to see this was a lot of work.  (Believe me, I know! :))

After a cursory glance, there are a few important changes that would need to be made for distribution in the factory banks:

* [Program numbers need to conform to UACC where possible](http://reaticulate.com/reabank.html#program-numbers).  Admittedly it's often a judgment call, but there are some clear cases, e.g. spiccato is program 42, pizzicato is 56, etc.
* Program names are lowercase everywhere in the current factory banks (except to differentiate e.g. trills m2 and trills M2)
* Group 1 should be used for the main articulation group, and the other groups used for modifiers, but e.g. the Celli bank uses group 1 for legato and most of the articulations are in group 2
* Celli is spelt wrong ;)
* I think in most cases the 'm' attribute is unnecessary, e.g. when it just reiterates the patch name.  'm' is optional, and its main purpose is to provide special instructions to the user when the patch needs to be adjusted to work with the bank.

TBone: is that what GPO calls it, not Trombone?

All that said, I think I can sort out what would need to be done to fix these up, so I'm happy to make the necessary changes.

**Comment by benignoc** [comment]
I can make those changes if you want. I thought it was mentioned in the video to use the same numbers as the note number used. That's what I used under that assumption anyway.

Anyway, let me know and I can at least take this work off you.

Anyway, program names are not exact with regards to the program names in the library. Tbone is one of them... that one I did just to shorten out, but for the rest I have done it to avoid useless information and duplication. For example the one called Violins, is the same used for Violin Solo KS and all the other KS violins within the library except for the GOS (which I have made a different program for). It is really pretty obvious if you have the library, there are not many confusions that can happen there.

What I have not done is build the Multi's that come with the library, because I don't think it would make sense to set them on the same track as are rather multi instrument rather than multi articulation. To me it does not make much sense anyway.

**Comment by benignoc** [comment]
[GPO5_v2.txt](https://github.com/jtackaberry/reaticulate/files/1517304/GPO5_v2.txt)

Ok, here goes with all the changes in place. Of course the UACC decissions I have made, are at times just an approximation but I think it should do nicely.

Let me know if you see anything wrong.

**Comment by jtackaberry** [comment]
@benignoc could you advise which CCs should be chased for GPO5?

For the next release Reaticulate is more selective about which CCs it chases by default, as CC chasing can cause problems.  Looking on Youtube videos I see mention of things like CC22 and 23 for variation, CC36 for depth, etc.  I thought it'd be better to ask someone who has the library than to guess from Youtube videos. :)

Thanks!

**Comment by jtackaberry** [comment]
Thanks for your contribution.  I've made the banks more broadly available to other users [here](https://github.com/jtackaberry/reaticulate/tree/master/userbanks).

Eventually we will have a proper website to share, discover, and import banks.  In the meantime, I'll socialize this location on GitHub.
