### ISSUE TITLE
Submitting user banks for Synchron Percussion I and II (drum maps also included)

### ISSUE THREAD

**Issue by seventh-sam** [jtackaberry/reaticulate#129]
Submitting Synchron Percussion I and II for the user bank section of this repository.  MIDI Note Name files are included as well.

[VSL_SYNPercussionI-II_RTBanks+Drummaps.zip](https://github.com/jtackaberry/reaticulate/files/5992253/VSL_SYNPercussionI-II_RTBanks%2BDrummaps.zip)

**Comment by jtackaberry** [comment]
Many thanks for the contribution @seventh-sam!  Will review this weekend.

**Comment by seventh-sam** [comment]
My pleasure!

**Comment by jtackaberry** [comment]
Just wanted to thank you @seventh-sam  for this and all your other contributions.  It was clearly a tremendous effort.  My apologies for taking so long to attend to it.
