### ISSUE TITLE
Reaticulate is crashed if icon description or color description is wrong

### ISSUE THREAD

**Issue by sasavranic** [jtackaberry/reaticulate#13]
Hi,

For example, while I'm creating new bank presets and I put some undefined icon, color descriptions, plugin will crash if you reload it.

I would suggest something like (pseudo):

`if color.exists? ? parse(color) : 'undefined color'`

That way we'll have just "undefined : undefined" on GUI, but we'll avoid crash.

**Comment by jtackaberry** [comment]
Thanks for the report.  Can you share the specific bank definition that triggered the crash?

**Comment by sasavranic** [comment]
Error is:

`...Data\Roaming\REAPER\Scripts\Reaticulate\\app\lib\rtk.lua:36: attempt to index a nil value (local 's')`

For example, instead:

```
//! c=textured i=fall o=cc:32,101
101 fall
```

you put this for color:

```
//! c=fall i=fall o=cc:32,101
101 fall
```

fall is non existent color in your array I suppose.

**Comment by jtackaberry** [comment]
Yep, makes sense.  Cheers.

**Comment by sasavranic** [comment]
https://github.com/jtackaberry/reaticulate/blob/master/app/articons.lua#L32

`return articons.icons[name] || 'undefined'`

**Comment by jtackaberry** [comment]
`articons.get()` should return nil for an unknown icon name.  Also that'd be unrelated to the color, but it's possible they both aren't as robust as they should be.

This is _supposed_ to be handled here: https://github.com/jtackaberry/reaticulate/blob/master/app/reabank.lua#L225

Specifically:
```lua
 local color = art.color or reabank.colors.default
-- [...]
 art.icon = articons.get(art.iconname or 'note-eighth')
```
So you can see the intention there.  Should be quite an easy fix, really, but I won't be in front of my DAW until tonight.

**Comment by jtackaberry** [comment]
Something like:

```lua
art.icon = articons.get(art.iconname) or articons.get('note-eighth')
```

should do.

At first blush, though, not sure why you're seeing problems with the color.  Will dig in tonight.

**Comment by jtackaberry** [comment]
Scratch that: yes, it's obvious why specifying an invalid color horks.  Easy fix there too.
