### ISSUE TITLE
Spitfire London Contemporary Orchestra Strings user-contributed bank for consideration.

### ISSUE THREAD

**Issue by burningcicada** [jtackaberry/reaticulate#133]
// Reabank file for Reaticulate - http://reaticulate.com/
//
// This file is a specially formatted Reabank file that is notated for use by Reaticulate.
// Specification can be found here:
//
//      http://reaticulate.com/reabank.html
//
//--------------------------------------------------------------------------------------
//! g="Spitfire/London Contemporary Orchestra Strings/Main" n="a-Violins and b-Violas"
//! m="Set patch to UACC. Use this for both Violins and Violas in main subfolder."
Bank 63 1 SSB - a-Violins and b-Violas
//! c=Vivid Long i=Vivid Long o=cc:32,1
1 Vivid Long
//! c=Vivid Spiccato i=Vivid Spiccato o=cc:32,42
42 Vivid Spiccato
//! c=Spectral Scrubs i=Spectral Scrubs o=cc:32,90
90 Spectral Scrubs
//! c=Long Sul Tasto i=Long Sul Tasto o=cc:32,17
17 Long Sul Tasto
//! c=Long Harmonics i=Long Harmonics o=cc:32,10
10 Long Harmonics
//! c=Long Super Pont i=Long Super Pont o=cc:32,96
96 Long Super Pont 
//! c=Staccato Dig i=Staccato Dig o=cc:32,49
49 Staccato Dig
//! c=Woozy Vib i=Woozy Vib o=cc:32,99
99 Woozy Vib
//! c=Percussive Pizzicato i=Percussive Pizzicato o=cc:32,103
103 Percussive Pizzicato
//! c=Open-Normale i=Open-Normale o=cc:32,94
94 Open-Normale
//! c=Open-Irregular Trem i=Open-Irregular Trem o=cc:32,93
93 Open-Irregular Trem
//! c=Open-Granular Trem i=Open-Granular Trem o=cc:32,91
91 Open-Granular Trem
//! c=Open-Gran to Norm i=Open-Gran to Norm o=cc:32,92
92 Open-Granular to Norm
//! c=Slackened Soft/Cresc i=Slackened Soft/Cresc o=cc:32,97
97 Slackened Soft/Cresc
//! c=Slack Crescendo i=Slack Crescendo o=cc:32,104
104 Slackened Crescendo
//! c=Twitchy i=Twitchy o=cc:32,101
101 Twitchy
//! c=Granular Trem i=Granular Trem o=cc:32,105
105 Granular Trem
//! c=Trem Sul Pont i=Trem Sul Pont o=cc:32,13
13 Trem Sul Pont

//--------------------------------------------------------------------------------------
//! g="Spitfire/London Contemporary Orchestra Strings/Main" n="c-Celli and d-Basses + Celli"
//! m="Set patch to UACC. Use for both Celli and Basses in main subfolder. Slackened range C2-C3" 
Bank 63 2 SSB - c-Celli and d-Basses + Celli
//! c=Vivid Long i=Vivid Long o=cc:32,1
1 Vivid Long
//! c=Vivid Spiccato i=Vivid Spiccato o=cc:32,42
42 Vivid Spiccato
//! c=Spectral Scrubs i=Spectral Scrubs o=cc:32,90
90 Spectral Scrubs
//! c=Long Harmonics i=Long Harmonics o=cc:32,10
10 Long Harmonics
//! c=Long Super Pont i=Long Super Pont o=cc:32,96
96 Long Super Pont
//! c=Woozy Vib i=Woozy Vib o=cc:32,99
99 Woozy Vib
//! c=Percussive Pizzicato i=Percussive Pizzicato o=cc:32,103
103 Percussive Pizzicato
//! c=Open-Normale i=Open-Normale o=cc:32,94
94 Open-Normale
//! c=Open-Irregular Trem i=Open-Irregular Trem o=cc:32,93
93 Open-Irregular Trem
//! c=Open-Granular Trem i=Open-Granular Trem o=cc:32,91
91 Open-Granular Trem
//! c=Open-Gran to Norm i=Open-Gran to Norm o=cc:32,92
92 Open-Granular to Norm
//! c=Long Slackened i=Long Slackened o=cc:32,97
97 Long Slackened
//! c=Short Slackened i=Short Slackened o=cc:32,104
104 Short Slackened
//! c=Twitchy i=Twitchy o=cc:32,101
101 Twitchy
//--------------------------------------------------------------------------------------

//! g="Spitfire/London Contemporary Orchestra Strings/Advanced/Extended Techniques" n="a-Violins and b-Violas-Long Tech"
//! m="Set patch to UACC. Use this for both Violins and Violas in Extended subfolder."
Bank 63 3 SSB - a-Violins and b-Violas-Long Techniques
//! c=Vivid Long i=Vivid Long o=cc:32,1
1 Vivid Long
//! c=Long Sul Pont i=Long Sul Pont o=cc:32,18
18 Long Sul Pont
//! c=Long Sul Tasto i=Long Sul Tasto o=cc:32,17
17 Long Sul Tasto
//! c=Long Harmonics i=Long Harmonics o=cc:32,10
10 Long Harmonics
//! c=Long Super Pont i=Long Super Pont o=cc:32,96
96 Long Super Pont
//! c=Spectral Scrubs i=Spectral Scrubs o=cc:32,90
90 Spectral Scrubs
//! Granular to Normal i=Granular to Normal o=cc:32,95
95 Granular to Normal
//! Slow Wide Vib i=Slow Wide Vib o=cc:32,98
98 Slow Wide Vib
//! c=Woozy Vib i=Woozy Vib o=cc:32,99
99 Woozy Vib
//! Wide Vibrato Quick i=Wide Vibrato Quick o=cc:32,100
100 Wide Vibrato Quick
//! c=Open-Gran to Norm i=Open-Gran to Norm o=cc:32,92
92 Open-Granular to Norm
//! c=Open-Granular Trem i=Open-Granular Trem o=cc:32,91
91 Open-Granular Trem
//! c=Open-Irregular Trem i=Open-Irregular Trem o=cc:32,93
93 Open-Irregular Trem
//! c=Open-Normale i=Open-Normale o=cc:32,94
94 Open-Normale
//! c=Twitchy i=Twitchy o=cc:32,101
101 Twitchy
//! c=Slackened Soft/Cresc i=Slackened Soft/Cresc o=cc:32,97
97 Slackened Soft/Cresc
//! c=Trem Sul Pont i=Trem Sul Pont o=cc:32,13
13 Trem Sul Pont
//! c=Granular Trem i=Granular Trem o=cc:32,105
105 Granular Trem
//--------------------------------------------------------------------------------------

//! g="Spitfire/London Contemporary Orchestra Strings/Advanced/Extended Techniques" n="a-Violins and b-Violas-Short Tech"
//! m="Set patch to UACC. Use this for both Violins and Violas in Extended subfolder."
Bank 63 4 SSB - a-Violins and b-Violas-Short Techniques
//! c=Vivid Spiccato i=Vivid Spiccato o=cc:32,42
42 Vivid Spiccato
//! c=Staccato Dig i=Staccato Dig o=cc:32,49
49 Staccato Dig
//! c=Percussive Pizzicato i=Percussive Pizzicato o=cc:32,103
103 Percussive Pizzicato
//! c=Short Harm i=Short Harm o=cc:32,61
61 Short Harm
//! c=Slack Crescendo i=Slack Crescendo o=cc:32,104
104 Slack Crescendo
//! c=Bridge Scrapes i=Bridge Scrapes o=cc:32,102
102 Bridge Scrapes

//!------------------------------------------------------------------------------------

//! g="Spitfire/London Contemporary Orchestra Strings/Advanced/Extended Techniques" n="c-Celli/d-Basses + Celli-Long Tech"
//! m="Set patch to UACC. Use this for both Celli and Basses in Extended subfolder."
Bank 63 5 SSB - c-Celli and d-Basses+Celli-Long Techniques
//! c=Vivid Long i=Vivid Long o=cc:32,1
1 Vivid Long
//! c=Long Harmonics i=Long Harmonics o=cc:32,10
10 Long Harmonics
//! c=Long Super Pont i=Long Super Pont o=cc:32,96
96 Long Super Pont
//! c=Spectral Scrubs i=Spectral Scrubs o=cc:32,90
90 Spectral Scrubs
//! Granular to Normal i=Granular to Normal o=cc:32,95
95 Granular to Normal
//! Slow Wide Vib i=Slow Wide Vib o=cc:32,98
98 Slow Wide Vib
//! c=Woozy Vib i=Woozy Vib o=cc:32,99
99 Woozy Vib
//! c=Open-Gran to Norm i=Open-Gran to Norm o=cc:32,92
92 Open-Granular to Norm
//! c=Open-Granular Trem i=Open-Granular Trem o=cc:32,91
91 Open-Granular Trem
//! c=Open-Irregular Trem i=Open-Irregular Trem o=cc:32,93
93 Open-Irregular Trem
//! c=Open-Normale i=Open-Normale o=cc:32,94
94 Open-Normale
//! c=Twitchy i=Twitchy o=cc:32,101
101 Twitchy
//! c=Long Slackened i=Long Slackened o=cc:32,97
97 Long Slackened

//!------------------------------------------------------------------------------------

//! g="Spitfire/London Contemporary Orchestra Strings/Advanced/Extended Techniques" n="c-Celli-Short Techniques"
//! m="Set patch to UACC. This patch included Bridge Scrapes."
Bank 63 6 SSB - c-Celli-Short Techniques
//! c=Vivid Spiccato i=Vivid Spiccato o=cc:32,42
42 Vivid Spiccato
//! c=Percussive Pizzicato i=Percussive Pizzicato o=cc:32,103
103 Percussive Pizzicato
//! c=Short Slackened i=Short Slackened o=cc:32,104
104 Short Slackened
//! c=Bridge Scrapes i=Bridge Scrapes o=cc:32,102
102 Bridge Scrapes

//!------------------------------------------------------------------------------------

//! g="Spitfire/London Contemporary Orchestra Strings/Advanced/Extended Techniques" n="d-Basses + Celli-Short Techniques"
//! m="Set patch to UACC"
Bank 63 7 SSB - d-Basses+Celli-Short Techniques
//! c=Vivid Spiccato i=Vivid Spiccato o=cc:32,42
42 Vivid Spiccato
//! c=Percussive Pizzicato i=Percussive Pizzicato o=cc:32,103
103 Percussive Pizzicato
//! c=Short Slackened i=Short Slackened o=cc:32,104
104 Short Slackened

//!------------------------------------------------------------------------------------

//! g="Spitfire/London Contemporary Orchestra Strings/Advanced/Individual Articulations" n="a-Violins"
//! m="Set patch to UACC"
Bank 63 8 SSB - Advanced/Individual Articulations
//! c=Granular Trem i=Granular Trem o=cc:32,105
105 Granular Trem
//! c=Open-Gran to Norm i=Open-Gran to Norm o=cc:32,92
92 Open-Granular to Norm
//! c=Open-Granular Trem i=Open-Granular Trem o=cc:32,91
91 Open-Granular Trem
//! c=Open-Irregular Trem i=Open-Irregular Trem o=cc:32,93
93 Open-Irregular Trem
//! c=Open-Normale i=Open-Normale o=cc:32,94
94 Open-Normale
//! Granular to Normal i=Granular to Normal o=cc:32,95
95 Granular to Normal
//! c=Long Harmonics i=Long Harmonics o=cc:32,10
10 Long Harmonics
//! c=Long Super Pont i=Long Super Pont o=cc:32,96
96 Long Super Pont
//! c=Slackened Soft/Cresc i=Slackened Soft/Cresc o=cc:32,97
97 Slackened Soft/Cresc
//! c=Spectral Scrubs i=Spectral Scrubs o=cc:32,90
90 Spectral Scrubs
//! c=Long Sul Pont i=Long Sul Pont o=cc:32,18
18 Long Sul Pont
//! c=Long Sul Tasto i=Long Sul Tasto o=cc:32,17
17 Long Sul Tasto
//! c=Twitchy i=Twitchy o=cc:32,101
101 Twitchy
//! Wide Vibrato Quick i=Wide Vibrato Quick o=cc:32,100
100 Wide Vibrato Quick
//! c=Woozy Vib i=Woozy Vib o=cc:32,99
99 Woozy Vib
//! c=Slow Wide Vib i=Slow Wide Vib o=cc:32,98
98 Slow Wide Vib
//! c=Short Harm i=Short Harm o=cc:32,61
61 Short Harm
//! c=Percussive Pizzicato i=Percussive Pizzicato o=cc:32,103
103 Percussive Pizzicato
//! c=Slack Crescendo i=Slack Crescendo o=cc:32,104
104 Slack Crescendo
//! c=Staccato Dig i=Staccato Dig o=cc:32,49
49 Staccato Dig
//! c=Bridge Scrapes i=Bridge Scrapes o=cc:32,102
102 Bridge Scrapes
//! c=Vivid Spiccato i=Vivid Spiccato o=cc:32,42
42 Vivid Spiccato
//! c=Trem Sul Pont i=Trem Sul Pont o=cc:32,13
13 Trem Sul Pont
//! c=Vivid Long i=Vivid Long o=cc:32,1
1 Vivid Long

//!------------------------------------------------------------------------------------

//! g="Spitfire/London Contemporary Orchestra Strings/Advanced/Individual Articulations" n="b-Violas"
//! m="Set patch to UACC"
Bank 63 9 SSB - Advanced/Individual Articulations
//! c=Granular Trem i=Granular Trem o=cc:32,105
105 Granular Trem
//! c=Open-Gran to Norm i=Open-Gran to Norm o=cc:32,92
92 Open-Granular to Norm
//! c=Open-Granular Trem i=Open-Granular Trem o=cc:32,91
91 Open-Granular Trem
//! c=Open-Irregular Trem i=Open-Irregular Trem o=cc:32,93
93 Open-Irregular Trem
//! c=Open-Normale i=Open-Normale o=cc:32,94
94 Open-Normale
//! Granular to Normal i=Granular to Normal o=cc:32,95
95 Granular to Normal
//! c=Long Harmonics i=Long Harmonics o=cc:32,10
10 Long Harmonics
//! c=Long Super Pont i=Long Super Pont o=cc:32,96
96 Long Super Pont
//! c=Slackened Soft/Cresc i=Slackened Soft/Cresc o=cc:32,97
97 Slackened Soft/Cresc
//! c=Spectral Scrubs i=Spectral Scrubs o=cc:32,90
90 Spectral Scrubs
//! c=Long Sul Pont i=Long Sul Pont o=cc:32,18
18 Long Sul Pont
//! c=Long Sul Tasto i=Long Sul Tasto o=cc:32,17
17 Long Sul Tasto
//! c=Long Tailpiece i=Long Tailpiece o=cc:32,106
106 Long Tailpiece
//! c=Twitchy i=Twitchy o=cc:32,101
101 Twitchy
//! Wide Vibrato Quick i=Wide Vibrato Quick o=cc:32,100
100 Wide Vibrato Quick
//! c=Woozy Vib i=Woozy Vib o=cc:32,99
99 Woozy Vib
//! c=Slow Wide Vib i=Slow Wide Vib o=cc:32,98
98 Slow Wide Vib
//! c=Short Harm i=Short Harm o=cc:32,61
61 Short Harm
//! c=Percussive Pizzicato i=Percussive Pizzicato o=cc:32,103
103 Percussive Pizzicato
//! c=Slack Crescendo i=Slack Crescendo o=cc:32,104
104 Slack Crescendo
//! c=Staccato Dig i=Staccato Dig o=cc:32,49
49 Staccato Dig
//! c=Bridge Scrapes i=Bridge Scrapes o=cc:32,102
102 Bridge Scrapes
//! c=Vivid Spiccato i=Vivid Spiccato o=cc:32,42
42 Vivid Spiccato
//! c=Trem Sul Pont i=Trem Sul Pont o=cc:32,13
13 Trem Sul Pont
//! c=Vivid Long i=Vivid Long o=cc:32,1
1 Vivid Long

//!------------------------------------------------------------------------------------

//! g="Spitfire/London Contemporary Orchestra Strings/Advanced/Individual Articulations" n="c-Celli"
//! m="Set patch to UACC"
Bank 63 10 SSB - Advanced/Individual Articulations
//! c=Open-Gran to Norm i=Open-Gran to Norm o=cc:32,92
92 Open-Granular to Norm
//! c=Open-Granular Trem i=Open-Granular Trem o=cc:32,91
91 Open-Granular Trem
//! c=Open-Irregular Trem i=Open-Irregular Trem o=cc:32,93
93 Open-Irregular Trem
//! c=Open-Normale i=Open-Normale o=cc:32,94
94 Open-Normale
//! Granular to Normal i=Granular to Normal o=cc:32,95
95 Granular to Normal
//! c=Long Harmonics i=Long Harmonics o=cc:32,10
10 Long Harmonics
//! c=Long Super Pont i=Long Super Pont o=cc:32,96
96 Long Super Pont
//! c=Long Slackened i=Long Slackened o=cc:32,97
97 Long Slackened
//! c=Spectral Scrubs i=Spectral Scrubs o=cc:32,90
90 Spectral Scrubs
//! c=Long Tailpiece i=Long Tailpiece o=cc:32,106
106 Long Tailpiece
//! c=Twitchy i=Twitchy o=cc:32,101
101 Twitchy
//! c=Woozy Vib i=Woozy Vib o=cc:32,99
99 Woozy Vib
//! Slow Wide Vib i=Slow Wide Vib o=cc:32,98
98 Slow Wide Vib
//! c=Percussive Pizzicato i=Percussive Pizzicato o=cc:32,103
103 Percussive Pizzicato
//! c=Short Slackened i=Short Slackened o=cc:32,104
104 Short Slackened
//! c=Bridge Scrapes i=Bridge Scrapes o=cc:32,102
102 Bridge Scrapes
//! c=Vivid Spiccato i=Vivid Spiccato o=cc:32,42
42 Vivid Spiccato
//! c=Vivid Long i=Vivid Long o=cc:32,1
1 Vivid Long

//!------------------------------------------------------------------------------------

//! g="Spitfire/London Contemporary Orchestra Strings/Advanced/Individual Articulations" n="d-Basses + Celli"
//! m="Set patch to UACC"
Bank 63 11 SSB - Advanced/Individual Articulations
//! c=Open-Gran to Norm i=Open-Gran to Norm o=cc:32,92
92 Open-Granular to Norm
//! c=Open-Granular Trem i=Open-Granular Trem o=cc:32,91
91 Open-Granular Trem
//! c=Open-Irregular Trem i=Open-Irregular Trem o=cc:32,93
93 Open-Irregular Trem
//! c=Open-Normale i=Open-Normale o=cc:32,94
94 Open-Normale
//! Granular to Normal i=Granular to Normal o=cc:32,95
95 Granular to Normal
//! c=Long Harmonics i=Long Harmonics o=cc:32,10
10 Long Harmonics
//! c=Long Super Pont i=Long Super Pont o=cc:32,96
96 Long Super Pont
//! c=Long Slackened i=Long Slackened o=cc:32,97
97 Long Slackened
//! c=Spectral Scrubs i=Spectral Scrubs o=cc:32,90
90 Spectral Scrubs
//! c=Twitchy i=Twitchy o=cc:32,101
101 Twitchy
//! c=Woozy Vib i=Woozy Vib o=cc:32,99
99 Woozy Vib
//! Slow Wide Vib i=Slow Wide Vib o=cc:32,98
98 Slow Wide Vib
//! c=Percussive Pizzicato i=Percussive Pizzicato o=cc:32,103
103 Percussive Pizzicato
//! c=Short Slackened i=Short Slackened o=cc:32,104
104 Short Slackened
//! c=Vivid Spiccato i=Vivid Spiccato o=cc:32,42
42 Vivid Spiccato
//! c=Vivid Long i=Vivid Long o=cc:32,1
1 Vivid Long

//!------------------------------------------------------------------------------------

//! g="Spitfire/London Contemporary Orchestra Strings/Other Patches" n="a-Violins-Light Resources"
//! m="Set patch to UACC. For Economic patches use Main Articulations subfolder."
Bank 63 12 SSB - a-Violins-Light resources
//! c=Vivid Long i=Vivid Long o=cc:32,1
1 Vivid Long
//! c=Vivid Spiccato i=Vivid Spiccato o=cc:32,42
42 Vivid Spiccato
//! c=Staccato Dig i=Staccato Dig o=cc:32,49
49 Staccato Dig
//! c=Percussive Pizzicato i=Percussive Pizzicato o=cc:32,103
103 Percussive Pizzicato

//!------------------------------------------------------------------------------------

//! g="Spitfire/London Contemporary Orchestra Strings/Other Patches" n="a-Violins-Time Machine"
//! m="Set patch to UACC"
Bank 63 13 SSB - a-Violins-Time Machine
//! c=Vivid Spiccato i=Vivid Spiccato o=cc:32,42
42 Vivid Spiccato
//! c=Staccato Dig i=Staccato Dig o=cc:32,49
49 Staccato Dig
//! c=Percussive Pizzicato i=Percussive Pizzicato o=cc:32,103
103 Percussive Pizzicato
//! c=Short Harm i=Short Harm o=cc:32,61
61 Short Harm
//! c=Slack Crescendo i=Slack Crescendo o=cc:32,104
104 Slack Crescendo
//! c=Bridge Scrapes i=Bridge Scrapes o=cc:32,102
102 Bridge Scrapes

//!------------------------------------------------------------------------------------

//! g="Spitfire/London Contemporary Orchestra Strings/Other Patches" n="b-Violas-Light Resources"
//! m="Set patch to UACC. For Economic patches use Main Articulations subfolder."
Bank 63 14 SSB - b-Violas-Light resources
//! c=Vivid Long i=Vivid Long o=cc:32,1
1 Vivid Long
//! c=Vivid Spiccato i=Vivid Spiccato o=cc:32,42
42 Vivid Spiccato
//! c=Staccato Dig i=Staccato Dig o=cc:32,49
49 Staccato Dig
//! c=Percussive Pizzicato i=Percussive Pizzicato o=cc:32,103
103 Percussive Pizzicato

//!------------------------------------------------------------------------------------

//! g="Spitfire/London Contemporary Orchestra Strings/Other Patches" n="b-Violas-Time Machine"
//! m="Set patch to UACC"
Bank 63 15 SSB - b-Violas-Time Machine
//! c=Vivid Spiccato i=Vivid Spiccato o=cc:32,42
42 Vivid Spiccato
//! c=Staccato Dig i=Staccato Dig o=cc:32,49
49 Staccato Dig
//! c=Percussive Pizzicato i=Percussive Pizzicato o=cc:32,103
103 Percussive Pizzicato
//! c=Short Harm i=Short Harm o=cc:32,61
61 Short Harm
//! c=Slack Crescendo i=Slack Crescendo o=cc:32,104
104 Slack Crescendo
//! c=Bridge Scrapes i=Bridge Scrapes o=cc:32,102
102 Bridge 

//!------------------------------------------------------------------------------------

//! g="Spitfire/London Contemporary Orchestra Strings/Other Patches" n="c-Celli-Light Resources"
//! m="Set patch to UACC. For Economic patches use Main Articulations subfolder."
Bank 63 16 SSB - c-Celli-Light resources
//! c=Vivid Long i=Vivid Long o=cc:32,1
1 Vivid Long
//! c=Vivid Spiccato i=Vivid Spiccato o=cc:32,42
42 Vivid Spiccato
//! c=Percussive Pizzicato i=Percussive Pizzicato o=cc:32,103
103 Percussive Pizzicato

//!------------------------------------------------------------------------------------

//! g="Spitfire/London Contemporary Orchestra Strings/Other Patches" n="c-Celli-Time Machine"
//! m="Set patch to UACC"
Bank 63 17 SSB - c-Celli-Time M
//! c=Vivid Spiccato i=Vivid Spiccato o=cc:32,42
42 Vivid Spiccato
//! c=Percussive Pizzicato i=Percussive Pizzicato o=cc:32,103
103 Percussive Pizzicato
//! c=Slack Crescendo i=Slack Crescendo o=cc:32,104
104 Slack Crescendo
//! c=Bridge Scrapes i=Bridge Scrapes o=cc:32,102
102 Bridge Scrapes

//!------------------------------------------------------------------------------------

//! g="Spitfire/London Contemporary Orchestra Strings/Other Patches" n="d-B+C-Light Resources"
//! m="Set patch to UACC. For Economic patches use Main Articulations subfolder."
Bank 63 18 SSB - d-B+C-Light resources
//! c=Vivid Long i=Vivid Long o=cc:32,1
1 Vivid Long
//! c=Vivid Spiccato i=Vivid Spiccato o=cc:32,42
42 Vivid Spiccato
//! c=Percussive Pizzicato i=Percussive Pizzicato o=cc:32,103
103 Percussive Pizzicato

//!------------------------------------------------------------------------------------

//! g="Spitfire/London Contemporary Orchestra Strings/Other Patches" n="d-B+C-Time Machine"
//! m="Set patch to UACC"
Bank 63 19 SSB - d-B+C-Time Machine
//! c=Vivid Spiccato i=Vivid Spiccato o=cc:32,42
42 Vivid Spiccato
//! c=Percussive Pizzicato i=Percussive Pizzicato o=cc:32,103
103 Percussive Pizzicato
//! c=Slack Crescendo i=Slack Crescendo o=cc:32,104
104 Slack Crescendo

//!------------------------------------------------------------------------------------

**Comment by jtackaberry** [comment]
Thanks for your contribution, @burningcicada.  This has now been added to the userbanks area.

**Comment by burningcicada** [comment]
My pleasure, more to follow. Thanks for a great tool!

**Comment by jtackaberry** [comment]
I was just taking a closer look at the bank and noticed that all the icon and color names are invalid.  I'm going to fix these (basically just be explicitly setting them to the defaults that Reaticulate will choose when there are errors), but if you do contribute banks in the future, you might want to take a look at the valid icon and color names here:

https://reaticulate.com/reabank.html

Thanks!

**Comment by jtackaberry** [comment]
Fixes applied.  See here for delta:

https://github.com/jtackaberry/reaticulate/commit/57cc07262f672c3820c00caa33a476c28edb9b77

**Comment by burningcicada** [comment]
Thanks for the dialogue and nudge. This library has a few icons that are
not listed from what is currently available. If you would like I could list
them for future reference otherwise I see your default fix as simple and
elegant. A question, if I wanted to change the icons as the attached
image how and where would I place the code. This is more of an aesthetic
question but also wondered if as a contributed bank not encouraged. Either
way appreciated. In the future I will email what I plan on contributing for
a second look.

Best,

J. Byron Wise

**Comment by jtackaberry** [comment]
Oh by all means feel free to open a ticket here for future contributions.  Email isn't necessary -- I am very happy to have a discussion here about possible improvements.

Unfortunately GitHub didn't pass through the image you attached to your email reply, so I'll have to use my imagination. :)

User-customized icons currently aren't supported.  I don't have any plans to implement that at the moment, as it would complicate and in some cases even preclude being able to share banks with other users.  Icons are tricky because of copyright. In Reaticulate's case, I screen-scraped the icons from Spitfire's GUI but got permission to redistribute with Reaticulate (under a non-free and non-transferable license) by the creator of those icons.

For the next version of Reaticulate, I've redone all the icons myself (using vector graphics for higher resolution) but there are still several icons that would still qualify as non-free because their _design_ is unique.  Spitfire can't copyright a quarter note, but they can certainly make an argument that their more esoteric icons (e.g. those for their experimental articulations that lack standard notation, such as those in Albion V) would be governed under copyright.

This means Reaticulate users will have to live with the icons not matching exactly what the libraries are using.  But I think the current set is rich enough that finding a reasonable approximation is straightforward.

**Comment by burningcicada** [comment]
Thank you for the explanation. I see your point in regards to copyright, as
well as customizations with icon colors.  As it is completed I will open a
ticket for the next. I just started on Sacconi Strings. I am curious to
know how you see harmonics, tremolo and trills in relation to your category
of FX and texture.

Best,

J. Byron

**Comment by jtackaberry** [comment]
The [docs](https://reaticulate.com/reabank.html#articulation-colors) aren't overly opinionated here but provide a bit of guidance:

> The factory banks use the light variants for articulations played more softly or subdued than normale, for example con sordino, sul tasto, or harmonics. The dark variants are used for grittier, distorted, or louder articulations, such as sul ponticello or Bartok pizzicato.

But the [factory banks](https://raw.githubusercontent.com/jtackaberry/reaticulate/0.4.6/Reaticulate-factory.reabank) offer some prior art in terms of colors:
- harmonics: long-light
- tremolo: long-dark
- tremolo con sord: long-light
- trills: long

This is just how I saw it.  Not super important that every bank follows this as it's admittedly subjective. :)

**Comment by burningcicada** [comment]
Thanks, that is helpful.

J. Byron
