### ISSUE TITLE
User banks for ODIN II Guitar and Djinnbass

### ISSUE THREAD

**Issue by AnshulJ999** [jtackaberry/reaticulate#135]
So I created reaticulate banks for ODIN II Guitar by Solemn Tones and Submission Audio's entire range of basses (Djinnbass, Punkbass, and Eurobass II). 

Here's the code: 

//----------------------------------------------------------------------------
//! g="Solemn Tones"
Bank 1 1 ODIN II Guitar

//! i=fx  o=note-hold:7
1 Tremolo Mode
//! i=fx  o=note:8
2 Percussive Chug
//! i=fx  o=note:9
3 Harmonics
//! i=fx  o=note:10
4 Tapping
//! i=fx  o=note:11
5 Scrapes
//! i=fx  o=note:12
6 Alt Pick
//! i=fx  o=note:13
7 Down Pick
//! i=fx  o=note:14
8 Up Pick 
//! i=fx  o=note:15
9 Alt Mute
//! i=fx  o=note:16
10 Down Mute
//! i=fx  o=note:17
11 Up Mute
//! i=fx  o=note:18
12 Bend Up Fast
//! i=fx  o=note:19
13 Bend Up Slow
//! i=fx  o=note:20
14 Bend Down Fast
//! i=fx  o=note:21
15 Bend Down Slow
//! i=fx  o=note:22
16 Slide Fast
//! i=fx  o=note:23
17 Slide Slow
//! i=fx  o=note:24

//----------------------------------------------------------------------------
//! g="Submission Audio"
Bank 2 1 Djinnbass

//! i=fx  o=note:0
19 Pick
//! i=fx  o=note:1
20 Hammer On
//! i=fx  o=note:2
21 Pull Off
//! i=fx  o=note:3
22 Slide Down Slow
//! i=fx  o=note:4
23 Slide Down Fast
//! i=fx  o=note:5
24 Slide Up Slow
//! i=fx  o=note:6
25 Slide Up Fast
//! i=fx  o=note:7
26 Dead Mute
//! i=fx  o=note:8
27 Harmonic Mute

(code end)

I guess someone might have to change some of the program change numbers to avoid conflict with other VSTs. I use these two exclusively so there's no issues for me. Also gotta say that Reaticulate has proven amazing to me so far, and helped me workflow a lot :)

**Comment by jtackaberry** [comment]
Thanks for the contribution! A few comments:

> //! i=fx o=note-hold:7
> 1 Tremolo Mode

Hm, I suspect this might not doesn't work.  It looks like this is intending to be a modifier for other articulations in the patch?  If so, you will probably need to separate tremolo on and tremolo off, and put them in another group.  Something like:

```
//! i=fx o=note-hold:7 g=2
1 Tremolo On
//! i=fx g=2
100 Tremolo Off
```

The "off" one having no output events will simply cause the held note from the tremolo on articulation to be released.  And because these are in another group, they work independently to the other ones (which are implicitly in group 1 as the `g` attribute hasn't been specified).

May be that the patch works different than I assumed though, in which if you can elaborate we can figure out the best way to capture this in the bank.

>  //! i=fx o=note:24

There are annotations here but no program following it.  Is the bank missing an articulation, or should this be removed?

I think in general too, while it's optional, adding a splash of color to the bank using the `c` attribute would be nice.  `c=long-dark` for tremolo, `c=short-light` for harmonics, etc.  Not super important though.

**Comment by AnshulJ999** [comment]
Hey Tack,
Thanks for replying. ODIN II's articulation system is really simple, and it just works based on the notes in the editor. There can only one running at a time. The term 'Tremolo mode' probably sounds a bit confusing, but it's just a variation of the 'Alt Pick' articulation where the instrument picks rapidly (like a real guitarist playing tremolo). It's the only one that requires a continuous note, whereas all the others are 'Latching' type articulations. 
I did forget to mention that ODIN II needs to be set in 'latching' mode for this to work, so that should be added in the notes area. There's a non-latching mode as well, but I prefer the latching mode for my workflow.
I tested both user banks properly before uploading them, so no worries about their functionality. Both are simple but very easy to use directly from the Arrange view (which is why I love it!). 

//! i=fx o=note:24
This line was extra. Forgot to remove it. You can remove this safely. 'Slide slow' is the last articulation for Odin. 
As for the effects icons and colors, I'm a total noob at coding so I just wanted a simple code that'd get my job done haha. So if you'd like to add some decoration to it, that'd definitely be great. But the thing with icons is I'm not sure which icons would be suitable for this since this is a guitar instrument and most of the icons I saw on Reabank's guide were designed for Orchestral instruments with classical symbols (I'm not a classical theorist myself so those are confusing to me). 

Lastly, I just had a quick question. Is there any way to remove a single instance of an articulation from reaticulate itself? So far, my workflow is to add the articulations in the arrange view which is super easy now, and I can visualize them very easily too. But to remove any of them, I have to go into edit mode and alt-click the PC number, and then add a new one. If there's any way to do this within Reaticulate (or perhaps I missed it), that'd be amazing. Thanks!

**Comment by jtackaberry** [comment]
> Lastly, I just had a quick question. Is there any way to remove a single instance of an articulation from reaticulate itself? So far, my workflow is to add the articulations in the arrange view which is super easy now, and I can visualize them very easily too. But to remove any of them, I have to go into edit mode and alt-click the PC number, and then add a new one. If there's any way to do this within Reaticulate (or perhaps I missed it), that'd be amazing. Thanks!

Oh wow, I'm really sorry I missed this @AnshulJ999.  Currently Reaticulate will replace any articulation under the editor cursor when you insert from the arrange view.  What kind of workflow would you think is best for your use case?

**Comment by AnshulJ999** [comment]
> > Lastly, I just had a quick question. Is there any way to remove a single instance of an articulation from reaticulate itself? So far, my workflow is to add the articulations in the arrange view which is super easy now, and I can visualize them very easily too. But to remove any of them, I have to go into edit mode and alt-click the PC number, and then add a new one. If there's any way to do this within Reaticulate (or perhaps I missed it), that'd be amazing. Thanks!
> 
> Oh wow, I'm really sorry I missed this @AnshulJ999. Currently Reaticulate will replace any articulation under the editor cursor when you insert from the arrange view. What kind of workflow would you think is best for your use case?

Haha no worries. It's been a while since I did any MIDI work in Reaper actually, but as far as I remember I wasn't able to remove incorrectly placed articulations very easily. And yes, replacing the articulation works fine. I think it was just difficult to delete the articulations from arrange view itself. Maybe a 'delete articulation' button in Reaticulate would help?

**Comment by jtackaberry** [comment]
> I think it was just difficult to delete the articulations from arrange view itself. Maybe a 'delete articulation' button in Reaticulate would help?

Perhaps a REAPER action "delete articulations in time selection or near edit cursor"?  Where "near" is defined as, say, on either side of one grid size unit, and it's used when there's no time selection?
