### ISSUE TITLE
Contributing banks for Synchron Brass (Vienna Symphonic Library) to repository

### ISSUE THREAD

**Issue by seventh-sam** [jtackaberry/reaticulate#137]
Enjoy!

[Synchron Brass Reaticulate Banks.zip](https://github.com/jtackaberry/reaticulate/files/6793353/Synchron.Brass.Reaticulate.Banks.zip)

**Comment by jtackaberry** [comment]
Sigh, how behind am I on user-contributed banks.  Well you know the deal by now: will work on this after 0.5 is out. :)
