### ISSUE TITLE
Contributing banks for free Orchestral Tools libraries

### ISSUE THREAD

**Issue by crenshawda** [jtackaberry/reaticulate#138]
Hope these help!

[Orchestral Tools Free Libraries Reaticulate Banks.zip](https://github.com/jtackaberry/reaticulate/files/6813337/Orchestral.Tools.Free.Libraries.Reaticulate.Banks.zip)

**Comment by jtackaberry** [comment]
Thanks much @crenshawda .  Apologies for such a long delay.
