### ISSUE TITLE
Contributing banks for Synchron Percussion I, II, and III

### ISSUE THREAD

**Issue by seventh-sam** [jtackaberry/reaticulate#142]
Drum Maps for use in Reaper are included as well.

[Synchron Percussion I-III - RT Banks and Drum Maps.zip](https://github.com/jtackaberry/reaticulate/files/7326114/Synchron.Percussion.I-III.-.RT.Banks.and.Drum.Maps.zip)

**Comment by jtackaberry** [comment]
Thanks for the contribution as always Sam.  I'll be attending to this after I get Reaticulate 0.5 final out the door.

**Comment by jtackaberry** [comment]
The inclusion of drum maps is an interesting conundrum.  This isn't really a problem Reaticulate solves currently, so distributing the drum maps along with the user banks is a bit cumbersome.

But I understand the use case, and wonder if this shouldn't be a first class feature in Reaticulate, where the reabank (we should probably just start calling these "articulation maps" now) includes the necessary details to dynamically construct the note name file and map it into the MIDI editor when the bank is assigned to the track

This is loosely related to #41, but whereas #41 entails defining CC names in the bank definition, this would involve assigning note names.  I've opened #166 and wouldn't mind if you shared your thoughts over there Sam, if you happen to have any.

Meanwhile I'll go ahead and just include the reabank, and just provide a reference in the comments that the drum maps exist.

**Comment by jtackaberry** [comment]
Had to make a tiny update: in the Performance articulation for Flexatone (very last one in the file), the icon name was `legato-phrase` which doesn't exist.  I changed it to `phrase`.  Everything else checked out. 👍
