### ISSUE TITLE
Rearticulate error on sub-projects with unfrozen midi. No Reaticulate usage.

### ISSUE THREAD

**Issue by audioplanet** [jtackaberry/reaticulate#145]
Whenever I leave a sub-project with some midi not frozen, I get this error
![Screenshot 2021-10-25 at 07 58 20](https://user-images.githubusercontent.com/18046361/138644287-df032585-5968-452e-a365-b581975d8857.png)
.
I don't use reticulate anywhere

**Comment by audioplanet** [comment]
I’ve resintalled a whole new computer and for the moment haven’t run into the problem. Will write if it comes back :)

Kris Górski
Audioplanet
t: +48728919933
***@***.*** | w: www.audioplanet.pl
Chat  Skype: kris.audioplanet

Music is movement in stillness

**Comment by audioplanet** [comment]
Hi

This happened again in a new project. I uninstalled reaticulate and still get the messgage.


Kris Górski
Audioplanet
t: +48728919933
***@***.*** | w: www.audioplanet.pl
Chat  Skype: kris.audioplanet

Music is movement in stillness

**Comment by jtackaberry** [comment]
Are you by chance using REAPER's program select dialog box to insert articulations and manually choosing the reabank file?

![image](https://user-images.githubusercontent.com/1280551/162447372-fd738133-6974-4a25-b20e-6132e587bea0.png)

That could cause this problem.

**Comment by audioplanet** [comment]
No. I don’t use it at all at any time. I opened the project in safe mode and it stopped asking that. Strange. I have uninstalled all rearticulate files before..

Kris Górski
Audioplanet
t: +48728919933
***@***.*** | w: www.audioplanet.pl
Chat  Skype: kris.audioplanet

Music is movement in stillness

**Comment by audioplanet** [comment]
What I want is just to be able to work without it installed, but despite it being uninstalled it keeps coming back :(

Kris Górski
Audioplanet
t: +48728919933
***@***.*** | w: www.audioplanet.pl
Chat  Skype: kris.audioplanet

Music is movement in stillness

**Comment by jtackaberry** [comment]
Can you send me the project?  You can attach it here, or [email it to me](mailto:tack@urandom.ca) if there's any sensitivity.

**Comment by audioplanet** [comment]
I can, though I found a workaround. I opened up every sub-project separately and re-saved. This made the dialog go away and now it doesn’t appear any more. As soon as I stumble upon it again I will.

Kris Górski
Audioplanet
t: +48728919933
***@***.*** | w: www.audioplanet.pl
Chat  Skype: kris.audioplanet

Music is movement in stillness
