### ISSUE TITLE
Contributing banks for Tokyo Scoring Strings (Impact Soundworks)

### ISSUE THREAD

**Issue by seventh-sam** [jtackaberry/reaticulate#149]
Luckily, only one bank is needed for this library.  Instructions in the zip file.
[RTBanks_TokyoScoringStrings_7thSam.zip](https://github.com/jtackaberry/reaticulate/files/7778500/RTBanks_TokyoScoringStrings_7thSam.zip)

**Comment by jtackaberry** [comment]
Will catch up with this after I get Reaticulate 0.5 final released.

**Comment by jtackaberry** [comment]
Made a small tweak before uploading: icon name `pizzicato` should be `pizz`.

Thanks as always Sam!
