### ISSUE TITLE
reaticulate failed to load JS plugin

### ISSUE THREAD

**Issue by daeavelwyn** [jtackaberry/reaticulate#15]
Hi,

First of all, really thanks for the effort made here to improve articulations into reaper !

So, I got an issue using reaticulate. To make sure this is not my configuration that interact with the plugin, I made a test with a portable installation of reaper. 

Here are the steps : 

1- I use the reapack procedure to install reaticulate, everything seems to be ok
2- open reaper
3- add a track
4- load reaticulate_main.lua
5- select track and click add reaticualte in the reaticulate window
6- plugin added but when I open FX window, plugin error is shown (see screenshot)

![reaticulate-issue](https://user-images.githubusercontent.com/4292225/33520455-83cfb034-d7bb-11e7-9c53-429d29b7c29d.PNG)

**Comment by jtackaberry** [comment]
Thanks for the feedback.  A couple questions:

1. This happens even after you restart Reaper?  (Your step 2 of "open Reaper" suggests so, but I want to clarify that you did restart Reaper after installing.  Not that it should be necessary, but want to rule it out.)
2. Does it happen if you manually insert the Reaticulate JSFX in the FX chain (same as you would any other FX)?

**Comment by daeavelwyn** [comment]
1- yes
2- ok, so, insering reaticulate JS from the FX window works. And once it has been done a first time, it works every next time I try (on the portable versin and on mys own configuration). So I guess loading manually the plugin the first time enables some stuff and then the plugin is ready to work for the next time.
It works even if I close/restart reaper for the next time....

**Comment by jtackaberry** [comment]
Thanks.  This is helpful.  I feel pretty confident this isn't a Reaticulate bug as such -- it's going to be something weird with either the Reaper or SWS API -- but I'll see if I can find some workaround.

**Comment by jtackaberry** [comment]
In fact, it's sufficient just to load the "Add FX" window without even inserting anything.

Now thinking this is technically probably a ReaPack issue.  ReaPack will install the JSFX, but it's not triggering a rescan of Reaper's FX cache, and so programatically adding the FX (as Reaticulate does) fails because Reaper doesn't know about it yet, until it rescans for FX.

I'll continue to look at a workaround, but tagging @cfillion for his thoughts.

**Comment by cfillion** [comment]
It works here if I add .jsfx to the FX name:

```
reaper.TrackFX_AddByName(tr, 'Reaticulate.jsfx', 0, 1)
```

You could also remove the .jsfx part in the ReaPack index file so the effect is installed as just Reaticulate.

**Comment by jtackaberry** [comment]
> It works here if I add .jsfx to the FX name:

Indeed, thanks @cfillion that does work.  And I'm more than a bit embarrassed that idea didn't occur to me.  :/
