### ISSUE TITLE
Contributing banks for VSL SyNCHRON-ized Special Edition 

### ISSUE THREAD

**Issue by flog426369** [jtackaberry/reaticulate#150]
I've coded 2 reabank files for the complete volumes 1, 2, 1 plus, 2 plus and 6 (dimension brass)
Just use it with default preset in Synchron player.

[VSL SYN-ized SE Volumes 1-2 plus Volume 6.zip](https://github.com/jtackaberry/reaticulate/files/7810779/VSL.SYN-ized.SE.Volumes.1-2.plus.Volume.6.zip)

This is the list of instruments supported.

----------------
Volumes 1-2 plus
----------------

02 Chamber strings/01 1st Violins 6 PLUS
02 Chamber strings/02 2nd Violins 6 PLUS
02 Chamber strings/03 Violas 4 PLUS
02 Chamber strings/04 Cellos 3 PLUS
02 Chamber strings/05 Double basses 2 PLUS
[VSL SYN-ized SE Volumes 1-2 plus Volume 6.zip]

02 Chamber strings/11a Chamber Str multi convolution
02 Chamber strings/11b Chamber Str flat stereo
03 Orchestral strings/01 1st Violins 14 PLUS
03 Orchestral strings/02 2nd Violins 14 PLUS
03 Orchestral strings/03 Violas 10 PLUS
03 Orchestral strings/04 Cellos 8 PLUS
03 Orchestral strings/05 Double basses 6 PLUS
03 Orchestral strings/11a Orchestral Str multi convolution
03 Orchestral strings/11b Orchestral Str flat stereo
01 Solo Strings/01 Violin 1 PLUS
01 Solo Strings/02 Violin 2 PLUS
01 Solo Strings/03 Viola PLUS
01 Solo Strings/04 Cello 1 PLUS
01 Solo Strings/05 Cello 2 PLUS
01 Solo Strings/06 Double Bass PLUS
06 Plucked instruments/01 Harp
06 Plucked instruments/03 Concert guitar
06 Plucked instruments/04 Overdrive
06 Plucked instruments/05 Upright bass
11 Flutes/01 Piccolo PLUS
11 Flutes/02 Flute 1 PLUS
11 Flutes/03 Flute 2 PLUS
11 Flutes/04 Alto Flute PLUS
11 Flutes/11 Flute-ens 3 PLUS
12 Oboes/01 Oboe (French) PLUS
12 Oboes/02 Oboe (Vienna) PLUS
12 Oboes/03 Oboe d amore PLUS
12 Oboes/04 English Horn I (French) PLUS
12 Oboes/11 Oboe-ens 3 PLUS
13 Clarinets/02 Clarinet Bb 1 PLUS
13 Clarinets/03 Clarinet Bb 2 PLUS
13 Clarinets/01 Clarinet Eb PLUS
13 Clarinets/04 Bass Clarinet PLUS
13 Clarinets/06 Basset horn PLUS
13 Clarinets/11 Clarinet-ens-3 PLUS
14 Bassoons/01 Bassoon 1 PLUS
14 Bassoons/03 Contrabassoon PLUS
14 Bassoons/14 Bassoons-ens-3 PLUS
15 Saxophones/02 Alto saxophone PLUS
15 Saxophones/03 Tenor saxophone PLUS
15 Saxophones/04 Baritone saxophone PLUS
21 Horns/01 Horn 1 (triple) PLUS
21 Horns/02 Horn 2 (Vienna) PLUS
21 Horns/11 Horn-ens 4 PLUS
21 Horns/12 Horn-ens 8 PLUS
22 Trumpets/01 Piccolo trumpet PLUS
22 Trumpets/02 trumpet 1 (C) PLUS
22 Trumpets/03 trumpet 1 (C) muted PLUS
22 Trumpets/11 trumpet-ens 3 PLUS
22 Trumpets/12 trumpet-ens 3 muted PLUS
23 Trombones/02 Tenor trombone PLUS
23 Trombones/03 Tenor trombone muted PLUS
23 Trombones/04 Bass trombone PLUS
23 Trombones/05 ContraBass trombone PLUS
23 Trombones/11 Trombone-ens 3 PLUS
23 Trombones/12 Trombone-ens 3 muted PLUS
24 low brass/02 Bass tuba PLUS
24 low brass/03 ContraBass tuba PLUS
24 low brass/04 Wagner tuba PLUS
31 Percussion/01 Timpani
31 Percussion/0 Bells
32 Keyboards and mallets/01 Bosendorfer
32 Keyboards and mallets/03 Konzerthaus organ
32 Keyboards and mallets/04 Harmonium
32 Keyboards and mallets/05 prepared piano
32 Keyboards and mallets/06 Celesta
32 Keyboards and mallets/14 Vibraphone

--------------------------
Volume 6 - Dimension Brass
--------------------------

25 Dimension brass/01 Horn Player
25 Dimension brass/01 Horn All Players
25 Dimension brass/02 Trumpet player
25 Dimension brass/02 Trumpet All Players
25 Dimension brass/03 Trombone player
25 Dimension brass/03 Trombone All Players
25 Dimension brass/04 Wagner tuba player
25 Dimension brass/04 Wagner tuba All Players
25 Dimension brass/05 Low Brass Player
25 Dimension brass/05 Low Brass All Players

Enjoy !

Flog

**Comment by jtackaberry** [comment]
Wow! What an effort! Thanks for the contribution, Frog.

Will catch up with this after I get Reaticulate 0.5 final out the door.

**Comment by jtackaberry** [comment]
Thanks again Flog.  Added the banks, though fixed a few cases where the icon name and color names were swapped (`c=legato-gliss i=legato`), and a line that was missing a comment marker.
