### ISSUE TITLE
EW Opus Keyswitch using "note" does not work

### ISSUE THREAD

**Issue by louisfeng** [jtackaberry/reaticulate#163]
I'm new to Reaper and Reaticulate (coming from Cubase). This is an amazing project. Thank you.

By default, Opus instruments have keyswitch assignments. I added the following to my user reabank file:

```
//! g="EastWest OPUS Brass" n="2 French Horn KS Master"
//! m=""
//! id=cbbdac4f-34a1-4a1d-86ea-3e9e00365d1f
Bank * * EastWest OPUS Brass - 2 French Horn
//! c=long i=note-whole o=note:12
1 Sus MAX
//! c=long i=note-whole o=note:13
2 Sus Accent MAX
```
The keyswitches are C0 and C#0. However Opus does not seem to respond.

Changing "note" to "cc" and modify the articulation assignments in Opus to CC worked OK. I tried "program' mode as well, but that didn't work either.

**Comment by louisfeng** [comment]
I want to add some new findings. I tried VSL Synchron player and notes work properly. So I don't think it's an issue in Reaticulate. 

I also found out that note:25 (C#1) triggers note C#0 in Opus. So it seems there's an offset in Opus. But my MIDI keyboard is triggering the right notes in Opus. Very weird.

**Comment by louisfeng** [comment]
Apparently, Reaper by default is offset by one octave from Opus. If I adjust the preference to offset by -1 octave, it will match with Opus, but now, VSL Synchron is off by 1 octave. :(

**Comment by louisfeng** [comment]
I found an option in VSL to set middle C to C3 instead of C4. Now they are consistent. I think problem solved. Hopefully this learning will be helpful to others.

**Comment by jtackaberry** [comment]
Thanks @louisfeng .  Yeah, the classic C3 vs C4 debacle, huh.  The good news at least is that the MIDI note numbers are unambiguous, once you figure out the right incantation to make the virtual instrument happy. :)

Glad you got it sorted.
