### ISSUE TITLE
Reaticulate_Main opens huge window on macOS

### ISSUE THREAD

**Issue by profittlich** [jtackaberry/reaticulate#168]
Running Reaticulate_Main.lua on macOS opens an extremely wide window. Trying to resize the window crashes Reaper.

Here's a video of the behavior:

https://user-images.githubusercontent.com/14078196/153730299-2fec38ff-c1e2-4729-922f-bd9801be5ad6.mp4

Tested on:

- 2021 MacBook Pro M1 Pro, macOS Monterey 12.1, Reaper 6.46, Reaticulate 0.5.2,  ReaPack  1.2.3.1, js_ReaScriptAPI 1.301, SWS as installed on 2022-02-12
- 2016 MacBook Pro i7, macOS BigSur, fairly recent Reaper+Extensions, Reaticulate 0.5.0

I think I did everything according to the installation instructions.

**Comment by jtackaberry** [comment]
Yep, definitely nothing you did here @profittlich  :)

I'm actually working this weekend on a fix.  This is being tracked on jtackaberry/rtk#8 if you're interested in the gory details (plus, as bonus content, my bitching and complaining about the situation on Mac :))

Given you're the second user running into this on Reaticulate, I think I'll push out a hasty works-well-enough-for-Reaticulate fix ASAP and then work on the more robust plumbing later.

**Comment by profittlich** [comment]
Awesome, thank you!

**Comment by jtackaberry** [comment]
@profittlich  would you be able to test out the latest prerelease of Reaticulate via the prerelease ReaPack?

https://reaticulate.com/prerelease.xml

I believe I have everything working solidly, but some additional eyeballs would be appreciated.

**Comment by profittlich** [comment]
It works!

**Comment by profittlich** [comment]
Thank you!

**Comment by jtackaberry** [comment]
Fix now released in 0.5.3.
