### ISSUE TITLE
Various Reabank Files

### ISSUE THREAD

**Issue by bradleybboone** [jtackaberry/reaticulate#17]
EastWest Hollywood Diamond
>very large library, only keyswitch patches mapped
>if someone feels up to creating the Strings & Percussion reabanks, that would be great!
[EastWest Hollywood Brass Diamond.txt](https://github.com/jtackaberry/reaticulate/files/1545191/EastWest.Hollywood.Brass.Diamond.txt)
[EastWest Hollywood Orchestral Woodwinds Diamond.txt](https://github.com/jtackaberry/reaticulate/files/1545119/EastWest.Hollywood.Orchestral.Woodwinds.Diamond.txt)

Impact Soundworks Bravura Scoring Brass
>all standard articulations mapped to UACC
>fx mapped in the cc32 90-100 range
[Impact Soundworks Bravura Scoring Brass.txt](https://github.com/jtackaberry/reaticulate/files/1545117/Impact.Soundworks.Bravura.Scoring.Brass.txt)

Native Instruments Session Horns Pro (Custom Keyswitch Setup)
>Requires the creation of custom 2 channel multi's to access all 14+ articulations per solo instrument (only 9 are assignable per channel)
> The reabank assumes you setup your keyswitches sequentially from C-1 in each channel
> I also recommend changing the dynamic control from velocity to CC11
[Native Instruments Session Horns Pro.txt](https://github.com/jtackaberry/reaticulate/files/1550333/Native.Instruments.Session.Horns.Pro.txt)

Native Instruments Symphony Series 
>some issues conforming fx and articulations to the UACC standard
>articulations "can" be mapped to a CC range in Kontakt, but not specific CC32 values
[Native Instruments Symphony Series Brass Ensemble.txt](https://github.com/jtackaberry/reaticulate/files/1545107/Native.Instruments.Symphony.Series.Brass.Ensemble.txt)
[Native Instruments Symphony Series Brass Solo.txt](https://github.com/jtackaberry/reaticulate/files/1545108/Native.Instruments.Symphony.Series.Brass.Solo.txt)
[Native Instruments Symphony Series String Ensemble.txt](https://github.com/jtackaberry/reaticulate/files/1545109/Native.Instruments.Symphony.Series.String.Ensemble.txt)
[Native Instruments Symphony Series Woodwind Ensemble.txt](https://github.com/jtackaberry/reaticulate/files/1545110/Native.Instruments.Symphony.Series.Woodwind.Ensemble.txt)
[Native Instruments Symphony Series Woodwind Solo.txt](https://github.com/jtackaberry/reaticulate/files/1545111/Native.Instruments.Symphony.Series.Woodwind.Solo.txt)

Orchestral Tools Metropolis Ark Series
>as above, some issues conforming to UACC standard with clusters & runs
>numerous keyswitch patches have extended patches in the individual instruments folder (like legato and extended fx). I listed them as separate banks with a channel output.
[Metropolis Ark1.txt](https://github.com/jtackaberry/reaticulate/files/1549584/Metropolis.Ark1.txt)
[Metropolis Ark2.txt](https://github.com/jtackaberry/reaticulate/files/1545114/Metropolis.Ark2.txt)

Spitfire BML Mural Strings Ensembles
[Spitfire BML Mural Symphonic Strings Ensembles.txt](https://github.com/jtackaberry/reaticulate/files/1545121/Spitfire.BML.Mural.Symphonic.Strings.Ensembles.txt)

(Updated Hollywood Brass Diamond - removed duplicate entry)
(Updated Metropolis Ark1 Low Strings Legato)
(Added NI Session Horns Pro & alphabetized this list by developer)

**Comment by jtackaberry** [comment]
Thanks for the submission Bradley!  At first blush it looks very good.  I'll review for inclusion in the factory banks in the next week or so.

I'm a little unsure about whether to include the Mural one though.  It's technical an abandoned product, and Spitfire Symphonic Strings as its successor is already in the factory banks.

Much appreciate the effort!

**Comment by bradleybboone** [comment]
Thank you for making this script open source! This is definitely a labor of love. 

I previously used Stephané's Inspector, so I have a fair about of reabank info already saved, it is just a chore to convert non-Spitfire libraries to UACC (clusters, bends, rips + shakes, multi vibrato types, etc.). The GUI editor will be a much welcome addition.

**Comment by Dynamosity** [comment]
Thanks for the banks Bradley. Also looking forward to the Bank Creator

**Comment by aaronventure** [comment]
Spitfire Harp KS (move the keyswitches all the way down or edit output to your preference/check bank number)

//! g="Spitfire" n="Harp"
Bank 1 1 Spitfire Harp

//! c=long i=note-eighth o=note:0
0 Normale
//! c=long-light i=harp-pdlt o=note:1
1 PDLT
//! c=long-light i=harmonics-natural-eighth o=note:2
2 Flageolet
//! c=long-light i=legato-slurred o=note:3
3 Slid
//! c=long-dark i=tremolo o=note:4
4 Bisbigliando
//! c=textured i=fx o=note:5
5 FX

**Comment by jtackaberry** [comment]
Thanks for your contribution.  I've made the banks more broadly available to other users [here](https://github.com/jtackaberry/reaticulate/tree/master/userbanks).

Eventually we will have a proper website to share, discover, and import banks.  In the meantime, I'll socialize this location on GitHub.
