### ISSUE TITLE
Feature request. Is it possible to offset a sample using keyswitch with reaticulate?

### ISSUE THREAD

**Issue by MapleTheFoxx** [jtackaberry/reaticulate#182]
I am wondering if there is a way we can offset the timing of a note, Example would be let's say Spitfire Studio Woodwinds marcato has an offset of -60. If there was a line of code to insert then put in the designated number is what i mean... Does this already exist? or would this be too difficult to implement maybe I am asking too much.

**Comment by jtackaberry** [comment]
This is #130. It's actually challenging to implement this as it requires Reaticulate to queue all events and replay them at the appropriate time. I've tried to implement this twice and have run into hurdles that cause me to pause and rethink. Lots of tricky edge cases involved here, especially when changing articulation with very different delays.

Anyway, on the roadmap to be sure, but not for the next major release.
