### ISSUE TITLE
Viena Symphonic Library - Special Edition Vol 1

### ISSUE THREAD

**Issue by benignoc** [jtackaberry/reaticulate#19]
Hello,
    Here I leave you a bank for VSL se1 
[VSL-SE1_Matrix_reabank.txt](https://github.com/jtackaberry/reaticulate/files/1547249/VSL-SE1_Matrix_reabank.txt)

   I will probably be working on the Vol-1 plus and in the VI-Pro 2 Matrix as soon as I find the time. But there are lots of patches there... so I need to regain my breath first.

    Enjoy, and thanks again for this nice plugin.

**Comment by jtackaberry** [comment]
Thanks for your contribution.  I've made the banks more broadly available to other users [here](https://github.com/jtackaberry/reaticulate/tree/master/userbanks).

Eventually we will have a proper website to share, discover, and import banks.  In the meantime, I'll socialize this location on GitHub.
