### ISSUE TITLE
Red Room Audio Palette with BP1 Melodics

### ISSUE THREAD

**Issue by blawler** [jtackaberry/reaticulate#22]
[Sonuscore TheOrchestra 042318.txt](https://github.com/jtackaberry/reaticulate/files/1940056/Sonuscore.TheOrchestra.042318.txt)

Here is a profile for Sunuscore's "The Orchestra" v 1.1

[Palette 042318.txt](https://github.com/jtackaberry/reaticulate/files/1939652/Palette.042318.txt)

New version for Palette 1.1 which was released April 2018.  NO changes to the Sketchpad library but several new articulations and one new instrument for Brush Pack 1 (Melodics)

[Palette 030818.txt](https://github.com/jtackaberry/reaticulate/files/1795713/Palette.030818.txt)
Bank numbers will probably need adjusting. 
Updated to use layered articulations.

[Palette.txt](https://github.com/jtackaberry/reaticulate/files/1613340/Palette.txt)

**Comment by jtackaberry** [comment]
Appreciate the submission @blawler!  A bit slow in getting to the next release but these banks look pretty good to me at first skim.  (Yep I'll tweak the bank numbers to be within the factory assigned range.)

Cheers!

**Comment by jtackaberry** [comment]
@blawler could you advise which CCs should be chased for these banks?  The next version of Reaticulate allows this to be customized per bank, so I'd like to make sure I have the right list.

Thanks!

**Comment by blawler** [comment]
@jtackaberry Hi Jason.  I am not sure about this one.  The Palette/Kontakt UI allows user customized CC assignments, so I guess it could be any of them?  There are NO default CC mappings as far as I can tell.  Only the keyswitches are implemented.  (All I have ever used are keyswitches). There is the admonition excerpted from the documentation below that CC 124-127 are used "internally".   ALSO- Note that the publisher just released an update about a week ago with new instruments and articulations, so I have to update the mapping.



...

_CC: When this is selected the articulation is triggered by the MIDI CC you set in the first box, and only when you play within the range determined by the next two boxes.
*WARNING* - CC’s 124-127 are forbidden as they are used internally and may cause a MIDI feedback loop that could result in a crash.

_

**Comment by jtackaberry** [comment]
Thanks for your contribution.  I've made the banks more broadly available to other users [here](https://github.com/jtackaberry/reaticulate/tree/master/userbanks).

Eventually we will have a proper website to share, discover, and import banks.  In the meantime, I'll socialize this location on GitHub.
