### ISSUE TITLE
"Note off" not being sent properly when switching to "shorts" 

### ISSUE THREAD

**Issue by rjd1961** [jtackaberry/reaticulate#230]
Weird thing occurring, I am using East West Hollywood Orchestra, set up user profile with articulations on different channels.  Articulations switch fine but "sometimes" when switching from long to short, the note off does not get sent for the last long note and the sustained note plays through even though the articulation has changed to short.  I have shortened the leading note considerably, as much as a 1/4 beat before the change and it still hangs.  Seems very strange, especially as in some sections it works perfectly but the next time the note hangs.  I couldn't find any other mention so not sure what is happening - I spent a lot of time setting up my banks so hopefully this is something simple I'm doing??  Or is there a way to set up a note off in the articulation switch?

**Comment by rjd1961** [comment]
OK as expected it was (my) user error; forgot I had copied the midi from a piano sketch with sustain pedal engaged so... yeah, all good once I deleted the hold pedal CC lane info.  Sorry, I will close this now.

**Comment by jtackaberry** [comment]
Glad it ending up being that simple @rjd1961. While reading your original post I was gearing up to ask you for a complete project file to reproduce the issue. :)

**Comment by rjd1961** [comment]
I'm very glad I didn't end up creating work for you over something so simple that I should have thought of it before posting instead of 15 minutes after.  Thanks.
