### ISSUE TITLE
Switching to default articulation when no keyswitch is pressed

### ISSUE THREAD

**Issue by Schroedingers-Cat** [jtackaberry/reaticulate#27]
There are instruments that use keyswitches merely for decorative and detailed articulations and are able to use all base articulations without keyswitches. That means, as soon as you release any keyswitch, you are back in default mode. However, when setting up a "Default" line in the reabank file to represent this status:
```
//! c=legato i=legato
14 Default
```
... the JSFX seems to filter out all MIDI input, which makes the instrument silent. 

Right now, I use the following workaround:
```
 //! c=legato i=legato o=note:0,0
14 Default
```
It works but seems unnecessary.

**Comment by jtackaberry** [comment]
Fair enough.  I used this work around in the Bohemian Violin as well (where the performer articulation is the default).  It's a simple workaround but it's technically not correct as note 0 is a valid note that may be used by another legitimate keyswitch, so this is a valid bug.
