### ISSUE TITLE
UI rule for adding Bank\programm by mouse-click

### ISSUE THREAD

**Issue by Levitanus** [jtackaberry/reaticulate#28]
It would be great to have a possibility of adding bank\pr change events to the midi-editor by mouse-click. May be, detect, if alt or control key is held as rule for not only swith, but place artic change under edit cursor.
It's a little bit tricky to find the proper bank in the list by hands now...

**Comment by jtackaberry** [comment]
It already works this way if step input is enabled, but I suppose you mean you'd like some shortcut/modifier to insert program changes even if step input is disabled in the MIDI editor?

**Comment by jtackaberry** [comment]
I chose to interpret it this way.  So right-clicking on an articulation will insert the program at the edit cursor (regardless of whether step input is enabled, or whether the MIDI editor is even open).
