### ISSUE TITLE
UACC CC#8 Spitfire Symphonic Strings doesn't switch to flautando

### ISSUE THREAD

**Issue by dtsmarin** [jtackaberry/reaticulate#34]
Everything works fine except the flautando articulation across the library for the CORE patches.

**Comment by jtackaberry** [comment]
This is fixed in the development branch but it's not in a release yet.  I will strive to push a release in the next few days.

**Comment by jtackaberry** [comment]
Actually, I'll close this since it's fixed in master.  It'll get picked up in the next release.
