### ISSUE TITLE
Transposition

### ISSUE THREAD

**Issue by YaakovDavis** [jtackaberry/reaticulate#51]
Some patches require transposition of the notes. For example, the "phrase builder" patches in the Voxos lib require the notes to be higher, compared to the legato patches. 

So when I switch from legato to staccato in a single voice, I have to alter the normal pitch, which complicates things.   

It's be nice if Reaticulate supported configurable transposition.

**Comment by jtackaberry** [comment]
Interesting idea!  I'm not sure if this should be a function of the output events though.  It sounds it should apply at the articulation level, and the output events which trigger the articulation aren't themselves transposed.

If you still think transposition should be a per output event feature, can you elaborate more on the use-case?

**Comment by YaakovDavis** [comment]
Yes, I did mean at the articulation level indeed; I got confused with the terminology.

**Comment by jtackaberry** [comment]
Folding this into #72 (whose scope is broader) and closing this one as a duplicate.
