### ISSUE TITLE
regression: artifact-note on after toggle-off

### ISSUE THREAD

**Issue by Levitanus** [jtackaberry/reaticulate#80]
https://youtu.be/-jmNjwkqnLM
after toggle-off the articulation invokes not only note-off msg, but also the same note-on
Reaper 5.984
Reaticulate 0.3.92
xubuntu 19.04
JS_Rescript extension is installed

**Comment by jtackaberry** [comment]
Can you please share the reabank used here?  This looks like correct behavior for note-hold output events, so I'm guessing you've got a different spec?

**Comment by Levitanus** [comment]
```
//! g="Bolder" n="Upright Bass"
Bank 05 1 Bolder - Upright Bass
//! c=long i=marcato o=note-hold:37 transpose=12
01 pick
//! c=long i=marcato-quarter o=note-hold:38 transpose=12
02 short attack
//! c=long i=staccato-dig o=note-hold:39 transpose=12
03 slap
//! c=long-light i=harmonics o=note-hold:40 transpose=12
04 harmonics
```

> This looks like correct behavior

Mmm, how to reorganize bank for make it not send the next note-on? )

**Comment by jtackaberry** [comment]
note-hold simulates holding the note while the articulation is active.  When you click onto a different articulation, it releases the note held by the previous articulation.  If you switch from 1 note-hold articulation to another, it will send the note-off for the previous one and send the note-on for the current one.  This looks to me exactly what it's doing, and that behavior is consistent with the last 0.3.x stable release as well.

>  Mmm, how to reorganize bank for make it not send the next note-on?

I'm not sure what you mean.  Will just a `note` output event type work?  This sends note-on and note-off immediately.

**Comment by Levitanus** [comment]
For example with this articulation:
```
//! c=long i=marcato o=note-hold:37 transpose=12
01 pick
```

at the fisrt press note-on (37) msg will be setn
at the second press note-off (37) msg, then note-on (37) msg will be sent.

I think this is how things are now and how they wasn't before :)

**Comment by jtackaberry** [comment]
> I think this is how things are now and how they wasn't before :)

That was the old behavior too.  I just tested it.

And to me it makes sense.  Retriggering the articulation should retrigger the underlying keyswitch.  If you didn't want that, why insert the second program change?

**Comment by Levitanus** [comment]
Agreed.

**Comment by jtackaberry** [comment]
Thanks Timofey.
