### ISSUE TITLE
404 errors when attempting to install via Reapack

### ISSUE THREAD

**Issue by ericgoetz** [jtackaberry/reaticulate#86]
I get a bunch of 404 errors when attempting to install Reaticulate via Reapack. I don't really know how the githubusercontent.com URL map back to your repo, but I don't see a release branch in your repo. Could that be the problem?

Thanks!
Eric

0 installed packages, 0 updates, 0 removed files and 75 errors

========== Errors: ==========

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/app/app.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/app/lib/middleclass.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/app/articons.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/app/lib/rtk.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/app/lib/utils.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/app/main.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/app/reabank.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/app/rfx.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/app/screens/banklist.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/app/screens/installer.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/app/screens/settings.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/app/screens/trackcfg.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Activate%20articulation%20by%20CC%20in%20group%201%20on%20default%20channel%20%28MIDI%20CC%20relative%20or%20mousewheel%29.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Activate%20articulation%20by%20CC%20in%20group%203%20on%20default%20channel%20%28MIDI%20CC%20relative%20or%20mousewheel%29.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Activate%20articulation%20by%20CC%20in%20group%202%20on%20default%20channel%20%28MIDI%20CC%20relative%20or%20mousewheel%29.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Activate%20articulation%20by%20CC%20in%20group%204%20on%20default%20channel%20%28MIDI%20CC%20relative%20or%20mousewheel%29.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Activate%20articulation%20by%20CC%20on%20channel%2001.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Activate%20articulation%20by%20CC%20on%20channel%2002.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Activate%20articulation%20by%20CC%20on%20channel%2003.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Activate%20articulation%20by%20CC%20on%20channel%2004.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Activate%20articulation%20by%20CC%20on%20channel%2005.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Activate%20articulation%20by%20CC%20on%20channel%2006.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Activate%20articulation%20by%20CC%20on%20channel%2008.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Activate%20articulation%20by%20CC%20on%20channel%2007.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Activate%20articulation%20by%20CC%20on%20channel%2009.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Activate%20articulation%20by%20CC%20on%20channel%2010.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Activate%20articulation%20by%20CC%20on%20channel%2011.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Activate%20articulation%20by%20CC%20on%20channel%2012.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Activate%20articulation%20by%20CC%20on%20channel%2013.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Activate%20articulation%20by%20CC%20on%20channel%2014.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Activate%20articulation%20by%20CC%20on%20channel%2015.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Activate%20articulation%20by%20CC%20on%20default%20channel.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Activate%20articulation%20by%20CC%20on%20channel%2016.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Activate%20next%20articulation%20in%20group%201%20on%20default%20channel.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Activate%20next%20articulation%20in%20group%202%20on%20default%20channel.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Activate%20next%20articulation%20in%20group%203%20on%20default%20channel.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Activate%20next%20articulation%20in%20group%204%20on%20default%20channel.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Activate%20previous%20articulation%20in%20group%201%20on%20default%20channel.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Activate%20previous%20articulation%20in%20group%202%20on%20default%20channel.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Activate%20previous%20articulation%20in%20group%203%20on%20default%20channel.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Main.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Activate%20previous%20articulation%20in%20group%204%20on%20default%20channel.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Set%20default%20MIDI%20channel%20by%20CC.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Set%20default%20MIDI%20channel%20to%2001.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Set%20default%20MIDI%20channel%20to%2002.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Set%20default%20MIDI%20channel%20to%2003.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Set%20default%20MIDI%20channel%20to%2004.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Set%20default%20MIDI%20channel%20to%2005.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Set%20default%20MIDI%20channel%20to%2006.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Set%20default%20MIDI%20channel%20to%2008.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Set%20default%20MIDI%20channel%20to%2007.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Set%20default%20MIDI%20channel%20to%2009.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Set%20default%20MIDI%20channel%20to%2011.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Set%20default%20MIDI%20channel%20to%2010.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Set%20default%20MIDI%20channel%20to%2012.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Set%20default%20MIDI%20channel%20to%2014.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Set%20default%20MIDI%20channel%20to%2013.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Set%20default%20MIDI%20channel%20to%2015.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/Reaticulate-factory.reabank:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/actions/Reaticulate_Set%20default%20MIDI%20channel%20to%2016.lua:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/img/add_circle_outline_white_18x18.png:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/img/arrow_back_white_18x18.png:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/img/articulations.png:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/img/delete_white_18x18.png:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/img/dock_window_white_18x18.png:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/img/edit_white_18x18.png:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/img/info_outline_white_24x24.png:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/img/keyboard_arrow_down_white_18x18.png:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/img/keyboard_arrow_up_white_18x18.png:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/img/settings_white_18x18.png:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/img/loop_white_18x18.png:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/img/undock_window_white_18x18.png:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/img/view_list_white_18x18.png:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/jsfx/Reaticulate.jsfx:
  404 Not Found

https://raw.githubusercontent.com/jtackaberry/reaticulate/release/img/warning_amber_24x24.png:
  404 Not Found

**Comment by jtackaberry** [comment]
I can't reproduce this.  Can you advise what Reaticulate Reapack URL you're using?

**Comment by jtackaberry** [comment]
Oh, I think you're using a very old URL.  Can you please switch to the one posted on the website?

https://reaticulate.com/release.xml

I'll fix the old ReaPack URL (that ends in index.xml) so it doesn't 404, but that one isn't being updated.

**Comment by ericgoetz** [comment]
Thanks for the fast response. Yeah, nice catch. I was watching the how-to video on my iPad and just manually typed the index.xml ReaPack URL from the video.

I used your release.xml URL and everything seems to be fine. I noticed some errors in the install window (pasted below), but they seem to be benign.

Thanks again! You can close this issue. I'll open another if I run into any more problems.
Eric

1 installed packages, 0 updates, 0 removed files and 49 errors

========== Errors: ==========

Scripts/Reaticulate/Reaticulate-factory.reabank:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/articulations.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-dark/18-add_circle_outline.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-dark/18-arrow_back.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-dark/18-checkbox-checked.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-dark/18-checkbox-intermediate.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-dark/18-checkbox-unchecked.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-dark/18-delete.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-dark/18-dock_window.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-dark/18-drag_vertical.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-dark/18-edit.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-dark/18-info_outline.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-dark/18-link.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-dark/18-loop.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-dark/18-pin_off.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-dark/18-pin_on.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-dark/18-search.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-dark/18-settings.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-dark/18-undock_window.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-dark/18-view_list.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-dark/24-alert_circle_outline.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-dark/24-drag_vertical.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-dark/24-info_outline.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-dark/24-resize_bottom_right.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-dark/24-warning_amber.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-dark/96-alert_circle_outline.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-light/18-add_circle_outline.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-light/18-arrow_back.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-light/18-checkbox-checked.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-light/18-checkbox-intermediate.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-light/18-checkbox-unchecked.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-light/18-delete.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-light/18-dock_window.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-light/18-edit.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-light/18-info_outline.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-light/18-link.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-light/18-loop.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-light/18-pin_off.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-light/18-pin_on.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-light/18-search.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-light/18-settings.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-light/18-undock_window.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-light/18-view_list.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-light/24-alert_circle_outline.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-light/24-drag_vertical.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-light/24-info_outline.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-light/24-resize_bottom_right.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-light/24-warning_amber.png:
  This script could not be registered in REAPER.

Scripts/Reaticulate/img/icons-light/96-alert_circle_outline.png:
  This script could not be registered in REAPER.

========== Installed packages: ==========

Reaticulate/MIDI Articulations/Reaticulate: an articulation management system for REAPER v0.4.5

**Comment by jtackaberry** [comment]
Thanks Eric.  I think I'll probably get rid of index.xml now as it's quite old and apparently broken anyway.  Cheers!
