### ISSUE TITLE
Error launching Reaticulate Main on fresh install

### ISSUE THREAD

**Issue by jackmau** [jtackaberry/reaticulate#87]
Hi,

I've been looking to try reaticulate for a while but when I installed latest version (0.4.5) via reapack (without any error message) I got the following error whenever trying to run Reaticulate main:

`\Roaming\REAPER\Scripts\Reaticulate\\app\lib\baseapp.lua:356: 'reaper.JS_Window_SetZOrder' argument 1: expected void`

I have latest SWS installed (v2.10.0) running reaper x64 (standard non-portable) on a x64 windows 7 machine. Tried to reinstall a couple of times with no success.
I was looking into the repo and I think it relates to this commit: ea9ee9057301547be1701925212bf54833230fd3

**Comment by jtackaberry** [comment]
@jackmau this is a bug inasmuch as Reaticulate isn't supposed to depend on the js_ReaScriptAPI extension, but it is erroring out anyway.

For now you can "fix" this by installing that extension.  More details here:

https://reaticulate.com/download.html#prerequisites

**Comment by jackmau** [comment]
@jtackaberry thanks for the shout, I actually had the js_ReaScriptAPI installed but I forgot to mention that. I updated to 5.99 and now Reaticulate works.
