### ISSUE TITLE
Bug report: Reaticulate 100% nonfunctional! 😣

### ISSUE THREAD

**Issue by globeril** [jtackaberry/reaticulate#91]
Hi, I'm using (or hoping to use) the latest version of Reaticulate over Reaper 6.08.

I used to work with Reaticulate on a previous version a few months back and everything went fine, but I had to reinstall recently. And so, no track configuration icon appears after adding JS: Reaticulate.jsfx at the top of the track's FX chain.

It shows "JS: Reaticulate.jsfx" on the left, and "Reaticulate is not enabled for this track <<Add Reaticulate FX>>". Clicking the button again does nothing.

I thought it might be a theme thing, but I get the same with the default ones too (and all others).

I uninstalled and reinstalled Reaticulate, the problem persists. What am I doing wrong please?

Also a weird thing that might be related. Clicking on Reaticulate's pencil and then "Edit in Notepad" opens notepad with an error: "Cannot find the D:\Programs\(music.txt file." (exactly as typed). I do have Reaper installed in D:\Programs, but it continues from there (to a folder titled "_(music & sound)_"—with the parenthesis. Could be those parenthesis fork things up for Reaticulate?

Also, when I hit "Show in Explorer" (under Reaticulate's pencil), it shows me _My Computer_, I suppose that's not the "folder" it was looking for. Re-clicking "Show in Explorer" does nothing. All in all, I suspect it's not properly installed. I installed it using the "https://reaticulate.com/release.xml" URL via ReaPack.

Thanks for your help!

**Comment by jtackaberry** [comment]
Hm, either it's the parens or it's the ampersand, that's a good theory.

You mentioned that you'd previously tried Reaticulate and it worked at that time.  Do you recall if your directory structure was different then?  Did you not have the `(music & sound)` subfolder?

Can you let me know the full path to where Reaper is installed?  Just want to make sure I try to reproduce properly.

**Comment by globeril** [comment]
Thanks for the prompt reply! The full path is a little embarrassing. Well, brace yourself:

D:\Programs\(music & sound)\_Reaper\_otr\OTR_v1_6_COMPLETE_R578SWS297 [REPACK 1]\FINAL STEP\OTR\reaper.exe

Yep. Guess I should do something about it, but let's see if that's actually what causes the problem.

I can't recall if it was int he same folder, or on my desktop as I just tried it out. Sorry! What do you think?

**Comment by globeril** [comment]
Alright. Got myself a fresh installation of Reaper on: `C:\Reaper`, re-installed Reaticulate as instructed on https://reaticulate.com/download.html, and the problem sadly persists. What could I possibly be doing wrong?

See screenshot at: https://i.ibb.co/gM1h4x7/reaticulate.jpg

**Comment by globeril** [comment]
SOLVED: it appears I had a bad installation of Reaper after all (including those that I reinstalled). I was using a seemingly corrupted version that came with OTR 1.7. If any other OTR user experiences this, I suggest re-downloading the installation, it worked for me. (OTR is ran by a single person, highly devoted yet one person, so we can't expect the amount of tests that we're commonly used to).

**Comment by jtackaberry** [comment]
Thanks @globeril for the sleuthing.  Glad you got things sorted out.  If you happen to understand anything about the technical nature of the problem, I'd be curious to know.  Otherwise, we'll just chalk it up to a random bit flip caused by a wandering neutrino. :)

**Comment by globeril** [comment]
Sure! I cannot just pop up when things aren't working then disappear when they do! You've been putting a lot of time and effort in Reaticulate and that's the very least I could do (along with some quick UI/UX design, hit me up on PM if needed).

I'm not quite sure what caused it to be honest. Perhaps a semi-corrupted portable installation of Reaper, perhaps an improper installation of Reaper/SWS/Reaticulate by myself over this new version, or maybe the `(` / `)` / `&` characters in the installation path, or a combination of some of the above. The new one I installed right at `C:\` so I haven't tested the last hypothesis yet.
