### ISSUE TITLE
Minor UI improvement

### ISSUE THREAD

**Issue by daeavelwyn** [jtackaberry/reaticulate#96]
Hi Jason,

I would like to know if it would be possible to add just a litlle option to see note value in decimal just next the note name while mouseover the articulation . It will help to write faster the note:DecimalValue in the reabank text file

A mockup here 
![Capture](https://user-images.githubusercontent.com/4292225/83975674-45386880-a8f5-11ea-9801-a2ab475c5203.PNG)

**Comment by jtackaberry** [comment]
Yes, sure, sounds reasonable.  And quite easy.

Also the difference between octaves in your screenshot (C7 in your articulation name vs Reaticulate showing C6) made me double check.  Of course there's a long standing conflict between whether middle C is C3 or C4, but Reaticulate should be aligning to Reaper, and it currently isn't.  So I'll fix that as well.

**Comment by daeavelwyn** [comment]
Hi Jason,
Thanks for this quick reply. Don't be worried by the C7 noted in my screenshot, it's an error on my side (C7 is written as a comment just next to the articulation name in the reabank file).

here is the cultpit : 

//! g="Orchestral Tools/Inspire 1" n="Brass Whole Ensemble"
//! m=""
Bank 4 2 OT-Inspire1 - Brass Whole Ensemble
//! c=legato i=note-whole o=note:108
1 Sustain - C7
//! c=legato i=note-whole  o=note:109
2 Sustain Soft - C#7
//! c=long-dark i=staccato o=note:111
5 Staccato - D#7
//! c=short i=marcato o=note:112
6 Marcato short - E7

**Comment by jtackaberry** [comment]
Oh I know it's what you specified in the articulation name, but the discrepancy between what you picked and what Reaticulate was showing in the statusbar made me check to see if Reaticulate was doing the right thing by looking at the note numbering in the MIDI editor.  Ultimately Reaticulate wasn't honoring the MIDI octave display offset in Reaper's settings, so I fixed that.

**Comment by daeavelwyn** [comment]
Ok, great ! I just installed the last github version and it works like a charm ! Thanks a lot, it really helps me to make a better assignment debugging :)
