### ISSUE TITLE
Reaticulate crashes when parsing Reabank file

### ISSUE THREAD

**Issue by madsonix7** [jtackaberry/reaticulate#98]
Hi there,

Today when I tried opening my latest Reaper sessions, I received the following ReaScript error message: 

...Data\Roaming\REAPER\Scripts\Reaticulate\\app\reabank.lua:311: attempt to perform bitwise operation on a nil value (field 'msb')

As such, I've been unable to open and use Reaticulate (which I've come to completely rely upon as part of my workflow).

I've made sure I have the latest versions of both Reaper and Reaticulate installed and have updated all ReaPack packages. Any further advice for how to get Reaticulate back up and running?

Thanks very much for your time! 

![Screenshot (20)](https://user-images.githubusercontent.com/57500531/84965292-9dc3fd00-b162-11ea-8e87-58c2aa1f4bdc.png)

**Comment by jtackaberry** [comment]
Can you please attach your `Reaticulate.reabank` (or [email it to me](https://urandom.ca/) if you're uncomfortable posting that in public)?  I strongly suspect a syntactical error in your Reabank that's causing Reaticulate to barf.

I do consider this a bug with Reaticulate though -- it should be more robust against such syntax errors and should never crash this way -- but in the short term, hopefully we can get you back up and running quickly.

**Comment by madsonix7** [comment]
Sure thing! I appreciate your reply and thanks for your help. Will this zip file work? GitHub won't let me attach the LUA file itself. 


[reabank.zip](https://github.com/jtackaberry/reaticulate/files/4795729/reabank.zip)

**Comment by jtackaberry** [comment]
@madsonix7 oops, I didn't mean `reabank.lua` but rather `Reaticulate.reabank`.  This can be found in the Data/ directory of your Reaper install, and it should called exactly `Reaticulate.reabank`.

**Comment by madsonix7** [comment]
Ah! Gotcha. Here it is. 

[Reaticulate.zip](https://github.com/jtackaberry/reaticulate/files/4795792/Reaticulate.zip)

**Comment by jtackaberry** [comment]
If you look at the very end of that file, notice:

```
//! g="Spitfire"
Bank 4
```

It's that half-finished Bank line that's causing the problem.  If you delete the quoted lines you should be good to go.

I'll leave this issue open so that I can make Reaticulate's reabank parsing code properly resilient to scenario.

**Comment by madsonix7** [comment]
Ah! No wonder. I was in the middle of editing a new bank yesterday. Thanks for that. Good to know that can happen.
